### ISSUE TITLE
allows amenity=waste_disposal areas

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#102]
I tried "waste", "disposal", "rubbish".

It is in preset.

**Comment by simonpoole** [comment]
Works for me ... I suspect the issue is that you hadn't selected a node but a way (for which it isn't) defined. IIRC this is the same as the original, is however a bit weirdly restrictive.

**Comment by matkoniecz** [comment]
> you hadn't selected a node but a way

That is what happened. I was tagging https://www.openstreetmap.org/way/598459318

I think that this tag can be used on ways - it makes sense, https://taginfo.openstreetmap.org/tags/amenity=waste_disposal has decent usage on ways, https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dwaste_disposal agrees that it can be used on closed ways.

**Comment by simonpoole** [comment]
Changed in https://github.com/simonpoole/beautified-JOSM-preset/commit/8e84934d07c496a9ffb3e7f25769875623a6066c
