### ISSUE TITLE
highway=path + bicycle=designated + foot=designated + segregated=no described as segregated

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#104]
![screenshot_2018-08-11-13-13-12-314_de blau android](https://user-images.githubusercontent.com/899988/43995939-fa942d62-9db8-11e8-97c3-1d153fa306a0.png)
![screenshot_2018-08-11-13-13-31-795_de blau android](https://user-images.githubusercontent.com/899988/43995940-fb75b548-9db8-11e8-9e03-938cabfe480e.png)

**Comment by simonpoole** [comment]
This is likely due to the preset matching code in vespucci, the good news is that in 11.1 (which features a major refactoring of the preset code) it works as expected. I'll see if there is any easy way to fix this in any case.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/ff52ca11ef63705e7b837b105f6da5eb37d1e4b2

**Comment by matkoniecz** [comment]
Thanks!
