### ISSUE TITLE
specify that capacity (for example of bicycle parking) is a number

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#106]
It would allow Vespucci to switch to numeric keyboard layout for entering values of such tags

**Comment by simonpoole** [comment]
There is a provision in the Vespucci extensions to indicate that a value is actually an integer number (and likely should show a number picker, not a numeric keyboard), however currently the value is ignored.

**Comment by simonpoole** [comment]
Hint that this is mostly an integer added in https://github.com/simonpoole/beautified-JOSM-preset/commit/d6e91a6b319fcdd18197476138091e05aab3cd16
