### ISSUE TITLE
make name optional for all pitches

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#107]
for example leisure=pitch, sport=volleyball treats name as mandatory

**Comment by simonpoole** [comment]
This was essentially already the case with the exception of 2-3 presets that didn't use the name_leisure_pitch chunk. Those couple of presets fixed in  https://github.com/simonpoole/beautified-JOSM-preset/commit/b2b417362cd5a53b1046d1b3b1757200b50c0f44
