### ISSUE TITLE
stop considering opening_hours as mandatory for amenity=school

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#109]
At least in Poland it is not something that really exists.

**Comment by HolgerJeromin** [comment]
Same apply for amenity=kindergarden (but have not checked it in the presets)

**Comment by simonpoole** [comment]
Fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/0f625c1ceb01e05d543abede6eaffe249a0c4ca7
