### ISSUE TITLE
make names optional for amenity=vending_machine with tickets

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#112]

**Comment by simonpoole** [comment]
The name tag is IMHO just present for ticket machines, not for the more general preset. No strong feeling about this.

**Comment by matkoniecz** [comment]
I think that it should not be mandatory also for this subset of ticket machines, but I also have no strong feelings.

**Comment by simonpoole** [comment]
Adressed in https://github.com/simonpoole/beautified-JOSM-preset/commit/c9bbcfe05a5ea9fa48431a17e721ec38126999b8
