### ISSUE TITLE
searching "dog" in vespucci should match leisure=dog_park

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#113]
I am not sure what should be changed - Vespucci search or is it case that should fixed by adding an alias.

**Comment by matkoniecz** [comment]
I have EN language set. I will test it and give more detailed info.

**Comment by matkoniecz** [comment]
I tried "dog" in English UK, English USA, English India, "pies", "psy" on Polish.

Neither gives this dog park result.

Vespucci 11.2.0-1, search for dog shows 7 results (I may attach screenshots if that would be helpful).

**Comment by simonpoole** [comment]
Well I get:
![screenshot_1541349144](https://user-images.githubusercontent.com/1011860/47966927-d2e80e00-e057-11e8-9c2b-427ceaa115e2.png)

**Comment by matkoniecz** [comment]
No, I have just default one installed. I will try reinstalling Vespucci.

**Comment by matkoniecz** [comment]
I reinstalled Vespucci, without any effects for searching "dog" in English UK.

Would it be helpful to post logged results, screenshots or to run a custom debugging build?

**Comment by simonpoole** [comment]
hmm "English UK"? Can you set the device to the default English aka US?

**Comment by matkoniecz** [comment]
I tried it already ( https://github.com/simonpoole/beautified-JOSM-preset/issues/113#issuecomment-435682225 ) but I will try again.

"dog" gives "horse racing", "cycling", "racetrack", "equestrian", "running"...

**Comment by simonpoole** [comment]
The dog park preset itself is present? If yes I'll need to make a custom build to get to the bottom of this (note the issue should really be in the vespucci repo).

**Comment by matkoniecz** [comment]
> The dog park preset itself is present?

Yes.

**Comment by simonpoole** [comment]
Does this issue still exist for you?

**Comment by matkoniecz** [comment]
![screenshot_2019-01-21-22-31-41-020_de blau android](https://user-images.githubusercontent.com/899988/51499945-81385f80-1dcc-11e9-94fe-400340128682.png)
![screenshot_2019-01-21-22-31-33-155_de blau android](https://user-images.githubusercontent.com/899988/51499946-81385f80-1dcc-11e9-92aa-c7d9542ac42d.png)

Yes.

**Comment by simonpoole** [comment]
Weird. Is the behaviour the same if you have a node, closed way or multi-polygon selected? Do you have any other presets installed?

**Comment by matkoniecz** [comment]
node, closed way and multipolygon gets exactly the same results

I have only default preset installed

**Comment by simonpoole** [comment]
This simply seems to have been a coincidence, if you have your device language set to English (but likely in no other one)  "dog" will match so many things (with 0 word matching distance) that dog_park simply isn't in the top 10.

I've tweaked the weighting a bit now so that sub-string matches get an even higher ranking, and now it turns up.

See https://github.com/MarcusWolschon/osmeditor4android/commit/c020e5a1f3565fea6c5e51af74056665eecd79ab
