### ISSUE TITLE
authorization tag for tobacco shop

### ISSUE THREAD

**Issue by fansanelli** [simonpoole/beautified-JOSM-preset#116]
the shop=tobacco doesn't suggests the "authorization" tag, can you please add it?

Moved from https://github.com/MarcusWolschon/osmeditor4android/issues/802

**Comment by simonpoole** [comment]
In principle no problem, but the wiki lacks any substantial information on what it is, further I suspect that it should really be "authorization_ref" if mainly a reference to a register number of similar, and not the type of authorization. Maybe running the idea past the folks on the tagging list first would be a good idea.

**Comment by fansanelli** [comment]
Hi Simon,
obliviously you are right...
I wrote a query: https://overpass-turbo.eu/s/DUY
and it's doesn't seems to be a standard adopted.
For now, I close this issue.
OT: I wrote you on OSM too yesterday...
