### ISSUE TITLE
advertising=column considered as "additional property"

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#123]
Following may be related:

advertising=column object in list of tags is listed as "additional property" despite that it a primary tag

it has no icon in tag list

nodes tagged with it have no icon in map view

**Comment by simonpoole** [comment]
There are different opinions if advertising is a top level tag or not, that's why it is neither in the hardwired list in Vespucci, nor currently in the additional "object_keys" in the preset. But I agree to be consistent it should be listed there.

**Comment by matkoniecz** [comment]
> There are different opinions if advertising is a top level tag or not

I am curious, how advertising column should be tagged according to this people? https://wiki.openstreetmap.org/wiki/Tag:advertising%3Dcolumn is not mentioning anything, https://taginfo.openstreetmap.org/tags/advertising=column#combinations has no useful info.

**Comment by simonpoole** [comment]
man_made=advertising
advertising=column

Aka the original scheme for advertising objects.

**Comment by matkoniecz** [comment]
https://taginfo.openstreetmap.org/tags/man_made=advertising#overview has 2 279 uses, man_made=advertising and advertising=column has 217 ( https://overpass-turbo.eu/s/Exv ), advertising=column has 9 152 ( https://taginfo.openstreetmap.org/tags/advertising=column#overview )

I think that in this case original proposal seems to be ignored for that part.

**Comment by simonpoole** [comment]
Added in https://github.com/simonpoole/beautified-JOSM-preset/commit/fb4c0de93e281be4039f01ce437bedf8e5bbb757
