### ISSUE TITLE
wind turbine finds no matching entries

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#126]
Also, `power=generator` + `generator:source=wind` is rendered without icon, so it is probably not just a missing alias.

**Comment by simonpoole** [comment]
works for me ....... (default preset as distributed with Vespucci). Do you have a link to a concrete object that is not rendered.

**Comment by simonpoole** [comment]
Ok what we match is 

power=generator
generator:source=wind
generator:method=wind_turbine

All three tags need to be present (and all three will be added if the corresponding preset is applied).

**Comment by simonpoole** [comment]
PS it seems a bit questionable that the preset suggests a name.

**Comment by matkoniecz** [comment]
>  generator:method=wind_turbine

Is it actually useful? Is there any method to generate power from wind that would not be a wind turbine?

I looked at existing data but from what I see ( http://overpass-turbo.eu/s/EOB ) everything looks like a tagging mistake - for example https://www.openstreetmap.org/note/1631367 and https://www.openstreetmap.org/note/1631368

**Comment by simonpoole** [comment]
Fixed (for all generator types) in https://github.com/simonpoole/beautified-JOSM-preset/commit/1a891f001d35df8ad22cfcb8b66dff09065406b8
