### ISSUE TITLE
Do not expect or suggest tagging name on waterway=riverbank

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#128]

**Comment by simonpoole** [comment]
?

**Comment by matkoniecz** [comment]
I encountered `waterway=riverbank` that had pink outline and info panel listed missing name as a problem.

AFAIK name tag should not be added to waterway=riverbank areas.

**Comment by simonpoole** [comment]
Fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/bdb3ea7cc41ad913e626410de5d1b8dc8f2d3462 (it is however in use a good 45'000 times)
