### ISSUE TITLE
Render ford icon on nodes

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#129]
Ford is listed as "additional property" when tagged on node of crossing road and waterway 

It may conflict with ford tagged on stretch of road but maybe like in https://github.com/simonpoole/beautified-JOSM-preset/commit/fb4c0de93e281be4039f01ce437bedf8e5bbb757 it can be considered as a primary key?

From what I see multiple primary tags on one object are not causing problems.

**Comment by simonpoole** [comment]
https://github.com/simonpoole/beautified-JOSM-preset/commit/c518ea4fd9fe12f1325e17bcd9ede170630692d6
