### ISSUE TITLE
Describe highway=bus_stop as "simple" not "legacy"

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#130]
In some situation highway=bus_stop may be described as "legacy" what in my opinion is a misleading term - it sound like something unwanted/deprecated/derogatory

As this is simple text replace and I am probably the only person what is irritated by this enough to make PR I plan to make a PR to that - let me know if that change would be unwanted

For example https://www.openstreetmap.org/node/4072526969/history#map=19/49.57697/20.78251

**Comment by simonpoole** [comment]
This is straight from JOSM iirc. I don't think we really have a way of expressing that this is an older variant of tagging, but still in use.

**Comment by matkoniecz** [comment]
What about traditional?

And in this case I think that it is OK to not focus on "older variant of tagging".

**Comment by simonpoole** [comment]
The bus stop item doesn't actually have any reference to "legacy" itself it is just in the "legacy" group.
