### ISSUE TITLE
stop considering wheelchairs, opening_hours, name keys as mandatory on building=church

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#134]
building=church includes abandoned or converted churches

this keys should be requested on amenity=place_of_worship objects

See https://www.openstreetmap.org/way/233355545#map=19/50.07631/19.93507 for an example

**Comment by simonpoole** [comment]
Where you removing tags from the building=church? Because a simply build=church on its own doesn't have OH or wheelchair tags in the preset.

**Comment by matkoniecz** [comment]
No. Simple building=church on its own requests OH, wheelchair and name. I may reinstall Vespucci to verify that nothing is borked.

I suspect that it is caused by

> <combo key="building" text="Building type" values="basilica,cathedral,chapel,church,temple" values_searchable="true"/>

as building=temple, building=basilica has the same effect

**Comment by simonpoole** [comment]
If that is the case then they should be matching as amenity=place_of_worship objects. Is that the case?

**Comment by matkoniecz** [comment]
> should be matching as amenity=place_of_worship objects

They are displayed as "church" with cross icon in viewing object detail. So I guess that it is "yes".

**Comment by simonpoole** [comment]
Weird. In any case I've removed matching on the building tag for those presets in https://github.com/simonpoole/beautified-JOSM-preset/commit/e8f65b96ccb89ef0a792068f6206100f2e74e1d2 , can you try and see if you see the same issue when using the updated default preset?

**Comment by matkoniecz** [comment]
Yes, it is fixed. Thanks!
