### ISSUE TITLE
ABC+ on "highway=service" adds tags

### ISSUE THREAD

**Issue by HolgerJeromin** [simonpoole/beautified-JOSM-preset#135]
A way with `highway=service`
gets:
````
service=driveway
tunnel=building_passage
layer=-1
````

Ref https://github.com/MarcusWolschon/osmeditor4android/issues/508

**Comment by simonpoole** [comment]
Not a preset issue - see https://github.com/MarcusWolschon/osmeditor4android/commit/838ebfa0841d873d2ec0861bae12d9d0861dce61
