### ISSUE TITLE
Missing translation context for cycleway=track

### ISSUE THREAD

**Issue by scaidermern** [simonpoole/beautified-JOSM-preset#138]
Coming from https://github.com/MarcusWolschon/osmeditor4android/issues/870

The German translation for the value `track` for the tag `cycleway=track` is wrong. `track` is translated to "Bahn" which doesn't really make sense. A better translation is "Bordsteinradweg" or Baulich abgesetzt".

According to @simonpoole this might be due to a missing translation context.

**Comment by simonpoole** [comment]
This was simply an old broken translation fixed: https://www.transifex.com/openstreetmap/presets/translate/#de/presetpot/127026615?q=text%3Atrack
