### ISSUE TITLE
Add ref to gates and subway entrances

### ISSUE THREAD

**Issue by contrapunctus-1** [simonpoole/beautified-JOSM-preset#142]
If I understand correctly, ref=* is often used in conjunction with these features.

**Comment by simonpoole** [comment]
gates as in public transport (for example in airports)?

**Comment by contrapunctus-1** [comment]
I meant barrier=gate and railway=subway_entrance, but it is possible airport gates have them too.

**Comment by simonpoole** [comment]
railway=subway_entrance already had a ref field https://github.com/simonpoole/beautified-JOSM-preset/commit/8313e9b33bda30609c675e086df962ca2789ec08 adds it for barrier=gate
