### ISSUE TITLE
Adding location= as suggestion for solar collectors

### ISSUE THREAD

**Issue by HolgerJeromin** [simonpoole/beautified-JOSM-preset#145]
https://wiki.openstreetmap.org/wiki/Key:location
for all
https://wiki.openstreetmap.org/wiki/Tag:generator:source%3Dsolar

**Comment by simonpoole** [comment]
Added in https://github.com/simonpoole/beautified-JOSM-preset/commit/e895b3ae4b55bd05b245c5116d3163ad94141a59

**Comment by HolgerJeromin** [comment]
oh, i forgot this issue :-)
was partly done in my PR #148

Just one note:
The old presets had `location=rooftop` for power cables, this new commit has `roof`.

**Comment by simonpoole** [comment]
Sorry missed this, the wiki doesn't seem to be very clear on roof vs. rooftop

**Comment by simonpoole** [comment]
@HolgerJeromin do we actually know now what the correct variant is?

**Comment by HolgerJeromin** [comment]
Roof has 107 19927.68

**Comment by simonpoole** [comment]
As roof is what I used, closing.
