### ISSUE TITLE
Add "gurudwara"

### ISSUE THREAD

**Issue by contrapunctus-1** [simonpoole/beautified-JOSM-preset#146]
Please add "Gurudwara" for amenity=place_of_worship+religion=sikh

**Comment by contrapunctus-1** [comment]
The Khanda symbol would be an optimal icon -  https://en.wikipedia.org/wiki/Khanda_(Sikh_symbol)

**Comment by simonpoole** [comment]
Added in https://github.com/simonpoole/beautified-JOSM-preset/commit/0f72d0fe068d3346f242d012cb0f26d528e4f622
