### ISSUE TITLE
Do not display atm=yes field for amenity=atm

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#152]
Currently it is displayed (at least when tagged) what is not useful and a bit confusing.

**Comment by simonpoole** [comment]
I'm not quite sure what you are referring to here, as the ATM preset -doesn't- contain atm=yes

**Comment by matkoniecz** [comment]
Maybe, but it is still listed in "additional properties" if tagged.

**Comment by simonpoole** [comment]
IMHO adding atm=yes to amenity=atm is a tagging mistake and needs no action here.
