### ISSUE TITLE
add cycleway:surface and footway:surface

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#154]
See https://taginfo.openstreetmap.org/keys/cycleway%3Asurface

**Comment by simonpoole** [comment]
Which presets should this be added too?

**Comment by matkoniecz** [comment]
Segregated combined footway and cycleway (`highway=path` + `bicycle=designated` + `foot=designated` + `segregated=yes`)

**Comment by simonpoole** [comment]
Added in https://github.com/simonpoole/beautified-JOSM-preset/commit/894043f297e5cc7d2853f3bba39e11db78767430
