### ISSUE TITLE
denomination=catholic should not be preset for historic=wayside_cross

### ISSUE THREAD

**Issue by CRCulver** [simonpoole/beautified-JOSM-preset#157]
When Vespucci autocompletes for a historic=wayside_cross POI, the tag denomination=catholic is added. This is not an appropriate generalization, inasmuch as Romania holds a significant amount of the wayside crosses in Europe and these are overwhelmingly denomination=orthodox.

**Comment by simonpoole** [comment]
While catholic is the default, you can naturally change the value, potentially this would be a case for setting the "use last value" flag.

**Comment by simonpoole** [comment]
https://github.com/simonpoole/beautified-JOSM-preset/commit/af00776d97f20a27727d4bcf76295a99f696ca7d sets the use_last_as_default flag so once you've set the denomination value once it will continue to use that  as  the default value.
