### ISSUE TITLE
Separate entries for certain preset terms

### ISSUE THREAD

**Issue by debyos** [simonpoole/beautified-JOSM-preset#158]
I have been translating presets for a while. It is really a great resource, thanks for creating and maintaining it.

A problem is that for some English terms there may be more than one Hungarian translations so please create separate [translatable entries](https://www.transifex.com/openstreetmap/presets/dashboard/) for following:
- operator:type=public (in Hungarian different from the generic "public" term)
- crossing:barrier=* (vs. generic "barrier")
Thanks!

**Comment by simonpoole** [comment]
Added translation context for operator:type in  https://github.com/simonpoole/beautified-JOSM-preset/commit/4b0253750786e52998b9c3e7f0bae66775c1c087 

crossing:barrier already has its own context.
