### ISSUE TITLE
Add octane_89 and octane_93 to fuel:type list

### ISSUE THREAD

**Issue by TimMagee** [simonpoole/beautified-JOSM-preset#159]
Currently, when selecting a fuel:type, two of the types that are almost always available in the USA are not shown.

In the USA, most gas stations have octane 87, 89, and 93. Please add octane_89 and octane_93 in order to allow easy mapping of US gas stations.

**Comment by simonpoole** [comment]
Added in https://github.com/simonpoole/beautified-JOSM-preset/commit/9271ec281651ea81904a753e9812f033e6f0ca52
