### ISSUE TITLE
Preset for "leisure=outdoor_seating" missing

### ISSUE THREAD

**Issue by chatelao** [simonpoole/beautified-JOSM-preset#165]
I use this tag, rendered as a pair of green chairs in the default map quite often:

- https://wiki.openstreetmap.org/wiki/Tag:leisure%3Doutdoor_seating
- https://wiki.openstreetmap.org/wiki/DE:Tag:leisure%3Doutdoor_seating

This is the icon showed on the map:
- https://wiki.openstreetmap.org/wiki/File:Outdoor_seating-14.svg

**Comment by simonpoole** [comment]
Added in https://github.com/simonpoole/beautified-JOSM-preset/commit/17f517da6d4acc73eeaee3862039a175a6ebafc9

**Comment by chatelao** [comment]
Thanks
