### ISSUE TITLE
amenity=doctors
Is unknown

### ISSUE THREAD

**Issue by vespucci-reporter** [simonpoole/beautified-JOSM-preset#166]
Description:
---

amenity=doctors should be usable parallel to the healthcare keys

Device info:
---
<table>
<tr><td>App version</td><td>14.0.0.2</td></tr>
<tr><td>App version code</td><td>1301</td></tr>
<tr><td>Android build version</td><td>T585XXU5CSB1</td></tr>
<tr><td>Android release version</td><td>8.1.0</td></tr>
<tr><td>Android SDK version</td><td>27</td></tr>
<tr><td>Android build ID</td><td>M1AJQ.T585XXU5CSB1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>gtaxllte</td></tr>
<tr><td>Device model</td><td>SM-T585</td></tr>
<tr><td>Device product name</td><td>gtaxlltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos7870</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>HolgerJeromin</td></tr>
</table>

**Comment by simonpoole** [comment]
I'm not quite sure what you mean with "unknown". 

Entering _doctor_ or _doctors_ in the preset search with return the "Doctor's Office" preset that sets both the amenity and the healthcare tags (the ship for just using one or the other has long sailed). What is correct is that it doesn't match if only one of the tags are present, this is likely not fixable without messing up matching for everything else.

**Comment by HolgerJeromin** [comment]
I had an element with amenity only. I was not sure if there was a typo in the key/value.

![rps20191021_153059_871](https://user-images.githubusercontent.com/2410353/67205210-e979a780-f417-11e9-8e67-7dc03d896fef.jpg)

**Comment by simonpoole** [comment]
https://github.com/simonpoole/beautified-JOSM-preset/commit/8f97f0bcf526acd0a620dada80e9e8be816c43c6 addresses this together with the support for min_match in vespucci 14.1
