### ISSUE TITLE
leisure=escape_game

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#170]
Synonyms include “escape game”, “escape room”, and “quest room”.

See https://github.com/openstreetmap/iD/issues/6447 for an equivalent iD issue

**Comment by simonpoole** [comment]
Added in https://github.com/simonpoole/beautified-JOSM-preset/commit/7c2ae08b2f77662bcf3b078103aaf221a57d2ded
