### ISSUE TITLE
attraction=summer_toboggan

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#172]
https://wiki.openstreetmap.org/wiki/Tag:attraction%3Dsummer_toboggan

seems to be currently missing

**Comment by simonpoole** [comment]
Not missing the attraction preset didn't include linear features, fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/1d57c248431bcc3bfbaeb44af4a445fa540d1c9d
