### ISSUE TITLE
Please add cash_withdrawal

### ISSUE THREAD

**Issue by HolgerJeromin** [simonpoole/beautified-JOSM-preset#173]
https://wiki.openstreetmap.org/wiki/Key:cash_withdrawal
At least for supermarkets.

**Comment by simonpoole** [comment]
Added in https://github.com/simonpoole/beautified-JOSM-preset/commit/04e8be7ec549d92c3eb01e62ad6aec6331290c15 even though the wiki entry is fundamentally broken.
