### ISSUE TITLE
Add highway=bus_stop to platform, not stop_position

### ISSUE THREAD

**Issue by Discostu36** [simonpoole/beautified-JOSM-preset#174]
At the moment, the preset for `public_transport=stop_position` suggests adding the legacy tag `highway=bus_stop`. This should be moved to the preset for `public_transport=platform` like documented in the wiki.

**Comment by simonpoole** [comment]
Re-arranged in https://github.com/simonpoole/beautified-JOSM-preset/commit/7c2ae08b2f77662bcf3b078103aaf221a57d2ded
