### ISSUE TITLE
Add "departures_board" key to platforms or stations

### ISSUE THREAD

**Issue by Mannivu** [simonpoole/beautified-JOSM-preset#175]
The key `departures_board` is a "[de facto](https://wiki.openstreetmap.org/wiki/Key:departures_board)" key for public_transport=platform and public_transport=station, so it would be useful to have it while editing platforms or stations.

**Comment by simonpoole** [comment]
The tag is not totally unproblematic as according to the wiki it is both an attribute tag and a top-level object tag (that is defines an object on its own) which makes consistent handling difficult.
