### ISSUE TITLE
Merge all iD presets

### ISSUE THREAD

**Issue by jidanni** [simonpoole/beautified-JOSM-preset#182]
In iD it is easy to enter Taoist temples, as
```
amenity=place_of_worship
religion=taoist
```
is found.

Perhaps all these great iD presets could be imported (by Vespucci staff, for all users, not each user by himself.)

**Comment by simonpoole** [comment]
No, we already compare what we have regularly with iD and JOSM. And we are not going to automatically add anything , because particularly in the case of iD it is very often nonsense.

In this specific case there is already a corresponding preset "Other place of worship".

**Comment by jidanni** [comment]
30% of China, most populous country in the world.
https://en.wikipedia.org/wiki/List_of_religious_populations#Taoists/Confucianists/Chinese_traditional_religionists

If there were no preset for 30% of America's, people would feel offended.
