### ISSUE TITLE
layer=-1 for underground parking 

### ISSUE THREAD

**Issue by opk12** [simonpoole/beautified-JOSM-preset#184]
I'm a new user of Vespucci and was directed here by the Vespucci new issue template.

I added a node with `amenity=parking parking=underground park_ride=no`. I uploaded the node to OSM. iD said the node `has incomplete tags` and clicking `upgrade tags` added `layer=-1`. It would be nice if it were added in Vespucci automatically.

**Comment by simonpoole** [comment]
Thanks for pointing this out.

https://github.com/simonpoole/beautified-JOSM-preset/commit/0eacd9f9ab289dbf7a48fee528c3c556a62ede4a adds layer and level tags (optionally) to the parking presets.

As to automatically setting layer: I don't believe that is a good idea. The layer value only has meaning relative to other OSM objects that are "over" or "under" the object in question, but not on their own or with any absolute semantics.
