### ISSUE TITLE
No name

### ISSUE THREAD

**Issue by vespucci-reporter** [simonpoole/beautified-JOSM-preset#186]
Description:
---

Is a Path not a street

Device info:
---
<table>
<tr><td>App version</td><td>14.1.4.0</td></tr>
<tr><td>App version code</td><td>1407</td></tr>
<tr><td>Android build version</td><td>root.20191015.112635</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>BV9700Pro_EEA_S41_V1.0_20191015V6</td></tr>
<tr><td>Device brand</td><td>Blackview</td></tr>
<tr><td>Device manufacturer</td><td>A-gold</td></tr>
<tr><td>Device name</td><td>BV9700Pro</td></tr>
<tr><td>Device model</td><td>BV9700Pro</td></tr>
<tr><td>Device product name</td><td>BV9700Pro_EEA</td></tr>
<tr><td>Device hardware name</td><td>mt6771</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by simonpoole** [comment]
WTF
