### ISSUE TITLE
Presets issue

### ISSUE THREAD

**Issue by TheAdventurer64** [simonpoole/beautified-JOSM-preset#188]
Description:
---

All presets should have a section for the address, contact information, and payment methods, instead of having to search the presets for the address, contact information, and payment methods manually.

Device info:
---
<table>
<tr><td>App version</td><td>14.1.4.0</td></tr>
<tr><td>App version code</td><td>1407</td></tr>
<tr><td>Android build version</td><td>136</td></tr>
<tr><td>Android release version</td><td>7.1.1</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>ONEPLUS A3010_28_171012</td></tr>
<tr><td>Device brand</td><td>OnePlus</td></tr>
<tr><td>Device manufacturer</td><td>OnePlus</td></tr>
<tr><td>Device name</td><td>OnePlus3T</td></tr>
<tr><td>Device model</td><td>ONEPLUS A3010</td></tr>
<tr><td>Device product name</td><td>OnePlus3</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[x86, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[x86, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by simonpoole** [comment]
Address, contact and payment information are very long presets with many fields, that is why they are provided as linked presets.

In JOSM these will be shown at the end of the preset tag form:

![grafik](https://user-images.githubusercontent.com/1011860/85839365-219d6b00-b79b-11ea-978d-3f101be67d5a.png)

In Vespucci in the MRU preset list:

![Screenshot_1593161896](https://user-images.githubusercontent.com/1011860/85840033-1dbe1880-b79c-11ea-98b9-ca13e3109674.png)

So they are really just one click away, no need to search for them.

**Comment by simonpoole** [comment]
No rsponse
