### ISSUE TITLE
Split translations for "branch"

### ISSUE THREAD

**Issue by debyos** [simonpoole/beautified-JOSM-preset#194]
Dear Developers,

please duplicate the translation for "branch" ([in the presets](https://github.com/MarcusWolschon/osmeditor4android/tree/7dc733fd9472d7db960b7b4bc04367b6ee0e2065/src/main/assets)): one for railways and another for banks.
Thanks

Gábor, a keen translator

**Comment by simonpoole** [comment]
This was don in https://github.com/simonpoole/beautified-JOSM-preset/commit/ab79ae59790eacc588695c3943d1cb6e2857b110 potentially the translations files haven't been updated, will check.
