### ISSUE TITLE
move <chunk id="wheelchair"> upwards

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#197]
The `<chunk id="wheelchair">` (code line 378) should be move upwards of `<chunk id="check_access_nomotor">` (code line 253) and `<chunk id="check_access_motor">` (code line 272), because it is referenced there and no wheelchair keys are displayed e.g. with barrier=entrance or barrier=gate and so on.

(I had this problem in Vespucci v15.0.2, and vespucci_preset.xml v1.9.6).

**Comment by simonpoole** [comment]
Fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/ae70563c7b078ba4af74951c69858f36d166f5a9
