### ISSUE TITLE
error with item="Survey Point"

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#198]
I think there is a syntax error in this line (vespucci_preset.xml v1.10.0):
            `<text key="name_ref" text="Reference"/>`

I guess it should be:
            `<text key="ref" text="Reference"/>` or
            `<reference ref="name_ref"/>`

And 2 suggestions: 

1. I would make ref (and name) **optional** to avoid standard validation errors in Vespucci (missing name/ref). Because many small survey_points which I saw (in Germany) don't have a reference value or a name. (I also wanted to add a ticket to the Vespucci repo since a longer time to support noref=yes like noname=yes to supress a "missing ref" validation error, if there is no ref. I think this key is not supported by the validation algorithm in Vespucci – and this concerns also other items, e.g. tourism=information/information=guidepost. Would be an alternative in this case if you want to keep the ref field non-optional.)
2. Add "plastic" to "material" (I saw many small survey points e.g. on ways in the forests of Germany made of plastic). Perhaps this was not the main intention of a "survey point", but I saw many of them mapped with this key, too. Why not ...

**Comment by simonpoole** [comment]
Error fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/2ce3374c2190a7e00f5381e3190ff93806f35e83

**Comment by simonpoole** [comment]
Could you add an image of a "plastic" survey point, it would seem to run counter to the purpose of the object.

**Comment by jajajaneeneenee** [comment]
Surely ... as I already wrote: perhaps this was not the main intention of a "survey point" ... but it is a survey point (in german "Vermessungspunkt") and other mappers seem to use it in Germany for such points …

![2020-05-08 17-23-48 Wanderung Urwald bei Von der Heydt](https://user-images.githubusercontent.com/48966999/95615528-aa999300-0a68-11eb-9b2a-47350a1a2213.jpg)

**Comment by simonpoole** [comment]
IMHO this is not really what a survey point in OSM is supposed to be (a survey point with known ref https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dsurvey_point), and use of it for these is similar to the natural=tree disaster, that is losing information about actual survey_points. I'll include plastic as material in any case.

**Comment by jajajaneeneenee** [comment]
Maybe you're right ... but maybe not ... I wouldn't be afraid as with the natural=tree problem. There are not so many survey points, not even small ones.

And the wiki text says also: "... or other piece of fixed equipment used by topographers". And these small points ARE fixed equipement, and they are used by topographers for subsequent measures I guess. Otherwise no one would put them somewhere. They are always fixed in a quite stable way with a thick, long metal spike under them – so it is intended for a longer life span IMHO. (They are also quite good orientation points e.g. in the forest, where I saw them quite often.)

And if such small points were not meant, then it would be a bad wording of this tag ... then it should have been called something like "man_made=triangulation_station". Or even "historic=triangulation_station". (See [https://en.wikipedia.org/wiki/Triangulation_station](https://en.wikipedia.org/wiki/Triangulation_station)). 

But it is in the man_made range ... Therefore (and generally in doubt) I would support a wider concept for the use for this tag, from very small to very large points, from complex to simple ones. The characteristics/specifics could be described with additional tags.

And did you take a look on the talk page of man made=survey point: [https://wiki.openstreetmap.org/wiki/Talk:Tag:man_made%3Dsurvey_point#Examples](https://wiki.openstreetmap.org/wiki/Talk:Tag:man_made%3Dsurvey_point#Examples)? This is from February 2020 ... so far, no one disagreed.

**Comment by simonpoole** [comment]
My issue is that survey points objects in OSM typically have a ref that at least in principle allows one to find out which position was (professionally) surveyed for it and move it there. This is not possible with these points so at beast their position is "rough", and without indicating that you don't know if its coordinates are at the "official" position of the point or just somewhere nearby.

**Comment by jajajaneeneenee** [comment]
That's true ... it's not the "master class" of survey points ... only a "simple class". But if no ref is tagged (like official coordinates), it should be clear that the position in OSM can only be "rough". And by the way I am not sure if every mapper would place a "master class" survey point exactly on the coordinates that are inscribed ... there could also be mistakes and confusion.

And often, these small ones are placed on borders of any kind. E.g. I saw some at borders of an official larger "forest graveyard" (= "Friedwald" in Germany), and so you can see by these points, where its borders are (at least "rough" – but without the points, you would have no idea at all sometimes). Or sometimes it's in the forest on the border of 2 villages or 2 (private/public) properties or at the border of a natural reserve or something like that. So it can also help as an indicator without inscribed coordinates.

I think it's not the worst example of what could be mapped ...

**Comment by simonpoole** [comment]
Plastic added as material value in https://github.com/simonpoole/beautified-JOSM-preset/commit/ecef0c169ecac32022b066e572a4328bc11e2778
