### ISSUE TITLE
Typo pyramdial instead of pyramidal 

### ISSUE THREAD

**Issue by HolgerJeromin** [simonpoole/beautified-JOSM-preset#20]
I found the typo in vespucci beta preset. 
Surprisingly there are only three entries in the osm database 
https://taginfo.openstreetmap.org/tags/roof%3Ashape=pyramdial

**Comment by simonpoole** [comment]
Fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/8205929ac327f5601460f6b27deae0d6575760b2

**Comment by HolgerJeromin** [comment]
Btw i fixed all three pois with this typo.

**Comment by simonpoole** [comment]
Thanks. The release the past week had a fix for the presets.

**Comment by HolgerJeromin** [comment]
Thats why i did the fix not earlier. I did not wanted to check more than once :)
