### ISSUE TITLE
Split 'speciality'

### ISSUE THREAD

**Issue by debyos** [simonpoole/beautified-JOSM-preset#204]
Hi,

there is ['speciality' both for butchers and dentists](https://github.com/simonpoole/beautified-JOSM-preset/tree/master/i18n). In Hungarian there should be something completely different, thus, please split them to have two separate 'specialities'. Thank you!

Gábor

**Comment by simonpoole** [comment]
Done in https://github.com/simonpoole/beautified-JOSM-preset/commit/8c8f45478f4b8bfe6a5f9b9fbe624b3fb75a6d43
