### ISSUE TITLE
Values missing for the the key 'board_type'

### ISSUE THREAD

**Issue by debyos** [simonpoole/beautified-JOSM-preset#205]
Hi,

when mapping touristic information board, the types of boards (e.g. wildlife, history, etc.) are [missing from the translation file](https://github.com/simonpoole/beautified-JOSM-preset/tree/master/i18n).
Please, set [them](https://wiki.openstreetmap.org/wiki/Key:board_type) there.

(If I remember well, they used to be there…)

Thank you

Gábor

**Comment by simonpoole** [comment]
Done in https://github.com/simonpoole/beautified-JOSM-preset/commit/234041d2c296e03e0b2c2d6a8eeb7e1b85af793f
