### ISSUE TITLE
Values missing for the key 'display'

### ISSUE THREAD

**Issue by debyos** [simonpoole/beautified-JOSM-preset#206]
Hi,

please, enter the values for the [key display](https://wiki.openstreetmap.org/wiki/Key:display) into the translation file.
Now, they appear only in English.
Thanks

Gábor

**Comment by simonpoole** [comment]
Done in https://github.com/simonpoole/beautified-JOSM-preset/commit/2fc21d5aee42472ee74435ac2e1c41ef4d276a4c
