### ISSUE TITLE
Update for HU translation

### ISSUE THREAD

**Issue by debyos** [simonpoole/beautified-JOSM-preset#207]
Hi,

using Vespucci, it seems that the [Hungarian translation on Transifex](https://www.transifex.com/openstreetmap/presets/language/hu/) (presets > Default) was last implemented several months (if not years) ago. Please update it soon.
Thanks in advance

_Gábor Babos_

**Comment by simonpoole** [comment]
The HU translations gets pulled with all the other ones, as long as it has more than the minimum required translations (5%) this should be automatic.
