### ISSUE TITLE
Redesign roundabout template

### ISSUE THREAD

**Issue by Mannivu** [simonpoole/beautified-JOSM-preset#208]
Roundabout template doesn't have some standard tag that can be useful and has some useless tags (see image below). I think it should be redesigned to add the `lit` and `surface` tags and remove the `oneway` tag (since is already implemented by the `junction=roundabout` tag and follows the roundabout direction) and the `overtaking` one.

<img src="https://user-images.githubusercontent.com/42747216/93336959-c07cb500-f828-11ea-9e3d-df797afa536d.jpg" width="250px"/>

**Comment by simonpoole** [comment]
Added in https://github.com/simonpoole/beautified-JOSM-preset/commit/929164ec2a408c3b4e6e308512293f11622caecc
