### ISSUE TITLE
Combo box suggestions can lead to large data errors (e.g. for power output)

### ISSUE THREAD

**Issue by danstowell** [simonpoole/beautified-JOSM-preset#209]
We just encountered a data issue caused by these suggested options for the power output, in our case for a solar panel installation:

     <combo key="plant:output:electricity" text="electricity" values="yes,2 W,3 kW,5 MW,7 GW"/>

(From [master_preset.xml](https://github.com/simonpoole/beautified-JOSM-preset/blob/master/master_preset.xml#L813))

I can see that the intention here is to show to users the correct formatting for the units (e.g. the capitalisation and the space before the units). In practice there's a risk that users will deliberately or accidentally click on these options, irrespective of whether they're the correct number for the situation.

This happened to us - a very experienced OSM contributor accidentally added 7 gigawatts of power to a rooftop, which is a very dramatic mistake (it would be about half of the UK's total solar generation capacity!)
https://www.openstreetmap.org/changeset/90137025

There may be a large number of more subtle data errors creeping in.

Is there any way, in your syntax, that those values (apart from "yes") can be designated as not being explicit suggestions but mere data formatting guidance?

**Comment by simonpoole** [comment]
The suggestions are from the JOSM original. You are correct that these probably should have the "editable" flag set so that they are only available as text suggestions and not as fixed value checkboxes.

**Comment by simonpoole** [comment]
Fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/37a25d3a7f13ce8394fcd46154f6999093cf7aab
