### ISSUE TITLE
payments: Bluepay > Clover

### ISSUE THREAD

**Issue by debyos** [simonpoole/beautified-JOSM-preset#211]
Hi,

according to [bluepay.com](https://bluepay.com), "Bluepay is now Clover". So it might be corrected in the presets as well.
Thanks

_Gábor_

**Comment by simonpoole** [comment]
Changed in https://github.com/simonpoole/beautified-JOSM-preset/commit/1cc3a2827e78c12b8a14530d52ee3806236bd0c0
