### ISSUE TITLE
Small improvements and corrections for v1.14.0

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#213]
Hello!

Here are some small things that could be improved or corrected in v1.14.0 IMHO.  I hope it's OK that I don't open an issue for every point, because these are quite small (mostly cosmetic) issues …

I only checked it in the xml for **Vespucci**, because I only use it there, so the line numbers are for "vespucci_preset.xml".

- [x] The chunk id="wikipedia_wikidata"  block has to be moved up I think (line 678). See line 519 `<chunk id="optional_name_wikipedia">` with reference.

- [x] Line 3482: item name="Wash" should be named "Car Wash" IMHO

- [x] Line 4239: missing checkgroup text at item name="Camp pitch", it could be: `<checkgroup text="Features" columns="2">`  (I think Vespucci will show single checkboxes instead of a checkgroup, if there is no text attribute.)

- [x]  "traffic_calming" is double in "object_keys". Perhaps you should sort it alphabetically to avoid that: `object_keys="advertising,attraction,cemetery,club,disused:amenity,disused:leisure,disused:man_made,disused:shop,ford,indoor,playground,police,public_transport,traffic_calming,traffic_sign,traffic_sign:backward,traffic_sign:forward"`

**Comment by simonpoole** [comment]
Thanks for the reports (better in individual issues though).

https://github.com/simonpoole/beautified-JOSM-preset/commit/b074ddacd5c5b107986feeeb7fad544180b0b92a fixes all of these except the third one, which was working at intended (5 and more items get displayed in a dialog per default,), but the way the label for the key was generated resulted in it being confusing, fixed in: https://github.com/MarcusWolschon/osmeditor4android/commit/2b247378ebd2c0236231a5b41de1dd8a81b36606

**Comment by jajajaneeneenee** [comment]
> Thanks for the reports (better in individual issues though).

OK, you really want for ever small small issue an individual issue? I will try ...

> [b074dda](https://github.com/simonpoole/beautified-JOSM-preset/commit/b074ddacd5c5b107986feeeb7fad544180b0b92a) fixes all of these except the third one, which was working at intended (5 and more items get displayed in a dialog per default,), but the way the label for the key was generated resulted in it being confusing, fixed in: [MarcusWolschon/osmeditor4android@2b24737](https://github.com/MarcusWolschon/osmeditor4android/commit/2b247378ebd2c0236231a5b41de1dd8a81b36606)

As intended? You mean, only checkgroups with 5 or more items get displayed as you would expect it with a checkgroup? So `<checkgroup>` is ignored with less than 5 items? A strange concept, IMO. If I code a checkgroup, I would like to have a checkgroup ... quite straight and simple. (E.g. for GUI reasons, to separate some checkboxes from others and summarize them, that's the function of a "group": grouping. Also with 2, 3 or 4 items ... only 1 would be quite stupid).

**Comment by simonpoole** [comment]
Check groups are never ignored, if they have less than the configurable number of checks they can be edited inline, if there are more they are edited in a modal/dialog.

**Comment by jajajaneeneenee** [comment]
Hmm .. then you perhaps misunderstood my third point. It was not shown as a checkgroup at all, because the text attribute was missing at the checkgroup – see  #196. Perhaps an image says more than words:

Now it looks like this – so checkgroup **IS IGNORED**:

![camp_pitch with checkgroup not OK](https://user-images.githubusercontent.com/48966999/97745897-d4832a00-1ae9-11eb-992c-48be3cf04aaa.jpg)

It should look like this (I mean I hope it should like this):

![camp_pitch with checkgroup OK (corrected)](https://user-images.githubusercontent.com/48966999/97745924-dcdb6500-1ae9-11eb-9b40-2a6301b68c2f.jpg)

**Comment by simonpoole** [comment]
As I said in my first response that was a labelling issue that has been fixed.

**Comment by jajajaneeneenee** [comment]
Ok ... then your first response was too hard to understand ... because it said "fixes all of these except the third one, which was working at intended " ... and it was **NOT** working as intended (at least in v15.0.5). See my screenshot ...
