### ISSUE TITLE
type error in item Shoe repair

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#214]
OK, you really want for ever small small  issue an individual issue (see #213)? I will try ...

Here (in v1.14.0):

`<link wiki="Tag:shop=shoe_repqir"/>` => should be `<link wiki="Tag:shop=shoe_repair"/>`

**Comment by simonpoole** [comment]
Fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/51faf3675fb92827def651bbb4574bf203bc281f
