### ISSUE TITLE
Suggestion for City Limit

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#216]
I would add the subkey "city_limit" to this item. I quite often see city-limit signs which are single-sided (e.g. on motorway_links) – there it makes sense to set "begin" or "end" ... it's more clear. See Wiki page [https://wiki.openstreetmap.org/wiki/Key:city_limit](https://wiki.openstreetmap.org/wiki/Key:city_limit).

E.g. in this way:
`<combo key="city_limit" values="begin,end,both" display_values="Begin,End,Both" values_sort="false" />`

**Comment by simonpoole** [comment]
Added in https://github.com/simonpoole/beautified-JOSM-preset/commit/cd8b2e08be9b37a3942ca0d683337acd78e5096a
