### ISSUE TITLE
Small problem with german translation of “designated” in v1.15.0

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#219]
There seems to be a wrong line in the german translation file for msgid "Designated" (v1.15.0):

```
msgid "Designated"
msgstr "<br><div>rechtsverbindlich vorgesehen / gewidmet<br data-mce-bogus=\"1\"></div>"
```

I think it should be like that:

```
msgid "Designated"
msgstr "Rechtsverbindlich vorgesehen / gewidmet"
```
(First letter upper case to be consistent with other translations like "Ja" or "Nein" or others ...)

Now it looks like that in Vespucci:

![Screenshot_20201109_040718](https://user-images.githubusercontent.com/48966999/98498856-3a895300-2248-11eb-997b-81f3b7a3cf6d.jpg)

**Comment by simonpoole** [comment]
Thanks. Fixed on transifex. I suspect the translator copy-pasted that from some HTML source in error.

In general you can simply fix things like that directly on transifex.
