### ISSUE TITLE
Wrong comment for stop sign (and confusing graycale icon for stop)

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#220]
```
        <item name="Stop sign" icon="highway_stop_18064.png" type="node" preset_name_label="true">
            <link wiki="Key:traffic_sign"/>
            <space/>
            <key key="traffic_sign" value="stop"/>
            <reference ref="traffic_signals_direction" /> 
        </item> <!-- Speed Limit -->
```

Should be:

```
        <item name="Stop sign" icon="highway_stop_18064.png" type="node" preset_name_label="true">
            <link wiki="Key:traffic_sign"/>
            <space/>
            <key key="traffic_sign" value="stop"/>
            <reference ref="traffic_signals_direction" /> 
        </item> <!-- Stop Sign -->
```

Additional note: 
I don't understand 100% why the stop sign icon is a grayscale icon, but e.g. the icon for "Speed Limit Sign" is coloured ... Feels inconsistent for me. For highway=stop I understand perhaps the grayscale icon (same icon as traffic_sign=stop), because it can also be used in situations without a stop sign. It took a while  for me in Vespucci to understand the difference between to 2 items "Stop" and "Stop sign", because they have the same icon ... a  little confusing ... especially if you use the search string "stop" and you get "Stop" and "Stop sign" with the same icon (and other items with the string "stop" of couse) – you have to guess (or know after a while) that "Stop" is "highway=stop". Not perfect … but I'm not sure how to solve that ...

**Comment by simonpoole** [comment]
Fixes in https://github.com/simonpoole/beautified-JOSM-preset/commit/523a8354924906a1b66f31ab75e32de998d7b45a and https://github.com/simonpoole/beautified-JOSM-preset/commit/c5fb9147ed75de550caf2ca69457085e4fa8fd6e
