### ISSUE TITLE
Stop requiring name and ref on solar panels

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#224]
Many small solar panels will have neither name nor ref adding `noname=yes` and I guess `noref=yes` to all of them is not useful

Example: https://www.openstreetmap.org/node/8153600083

**Comment by simonpoole** [comment]
The problem is that the tagging doesn't differentiate between large installations and small ones. Mapping small ones has really only recently became a thing.  

Addressed in https://github.com/simonpoole/beautified-JOSM-preset/commits/master
