### ISSUE TITLE
Alter waste basket/trash can waste options

### ISSUE THREAD

**Issue by davidpnewton** [simonpoole/beautified-JOSM-preset#226]
Currently the tagging for waste baskets/trash cans is three radio buttons, giving a choice of trash, cigarettes or dog waste. The problem with this is that it is false dilemma: many bins round where I live can take trash, cigarettes AND dog waste. Therefore being asked which one of three can be put in the bin is a false dilemma.

Please alter this from a radio button list to a check box list so that multiple types of waste can be marked as accepted by waste baskets/trash cans.

**Comment by simonpoole** [comment]
Fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/6a0dda366f20c1e62727d565c5168ed3c306ef5e
