### ISSUE TITLE
Hungarian tag translations missing

### ISSUE THREAD

**Issue by debyos** [simonpoole/beautified-JOSM-preset#229]
## Vespucci Version
15.1.2

## Download source
Google Play

## Device (Manufacturer and Model)
Samsung Galaxy S50

## Android Version 
10

## Behaviour/Symptoms
Hungarian translation of tag values do not appear for the key `generator:method`. 
However, the very same values appear in the next row, for the key `generator:type`:

![kép](https://user-images.githubusercontent.com/26843901/102700434-8e2a8b80-424d-11eb-9b8b-1829ae53e72f.png)

## Expected Behaviour
They should be there in Hungarian, all keys and all values.

**Comment by simonpoole** [comment]
https://github.com/simonpoole/beautified-JOSM-preset/commit/e140bf9dea6f9ed55bf9483daf0c942708ca71cf tries to add consistent display_values to the relevant presets, but they are a bit of a mess in the original JOSM version too.

**Comment by debyos** [comment]
Thank you for the quick response!
