### ISSUE TITLE
Tags that should be optional

### ISSUE THREAD

**Issue by simonpoole** [simonpoole/beautified-JOSM-preset#23]
- [x] name on landuse residential
- [x] ref on tertiary
- [x] service on highway=service (disputable)
- [x] name on fountain

**Comment by matkoniecz** [comment]
> service on highway=service (disputable)

Note https://wiki.openstreetmap.org/wiki/Tag:service%3Dparking_aisle#How_to_Map

> In an area with amenity=parking add these (often multiple) subordinated ways that allow access to the rows of parking spots with both
highway=service and service=parking_aisle.

> Add a oneway=* tag if appropriate.

> The main way(s) on the parking lot, for entering and connecting multiple parking_aisle, should be mapped with highway=service, only. 

I map using this method, it seems to be typical one in my experience.

**Comment by simonpoole** [comment]
Fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/874a0fa92494dca91df2b69dd0c4d4c3c3bc5f8c and https://github.com/simonpoole/beautified-JOSM-preset/commit/fd67168c67d6ea7377dded7163bc54ea930ff602
