### ISSUE TITLE
Add parking=street_side to amenity=parking preset

### ISSUE THREAD

**Issue by Discostu36** [simonpoole/beautified-JOSM-preset#234]
[parking=street_side ](https://wiki.openstreetmap.org/wiki/Tag:parking%3Dstreet_side) is now an approved tag to use for parking spaces that are located alongside a street.

**Comment by simonpoole** [comment]
THis was added in https://github.com/simonpoole/beautified-JOSM-preset/commit/2e077122ac990e081240033e4847d3d7db8eccf6
