### ISSUE TITLE
traffic_calming=island: type closedway is missing

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#241]
For traffic_calming=island (item name="Island" name_context="traffic_calming") you should add type="closedway".

Now it only has type node and way.

See Wiki page [https://wiki.openstreetmap.org/wiki/Tag:traffic_calming%3Disland](https://wiki.openstreetmap.org/wiki/Tag:traffic_calming%3Disland).

**Comment by simonpoole** [comment]
Thanks, fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/e24bfc8ef6d0359860a0a6f66a11825e9a155800
