### ISSUE TITLE
The icon of playground=swing is amenity_empty.png

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#242]
It should be at least "amenity_slide_30043.png" like other playground equipement ... It doesn't look nice in Vespucci on the map ...

(Of course it would be great if every playground equipment would have its own icon ... and another colour as the amenity brown ...). Perhaps something like this:

![playground_example](https://user-images.githubusercontent.com/48966999/108926765-5a018b80-763f-11eb-8ace-f38b282ca240.jpg)

**Comment by simonpoole** [comment]
Please feel free to create the icons and add them via PR (just the SVGs), you will probably need to simplify and increase stroke width so that they actually work on map.

Note: please only CC0 icon designs.
