### ISSUE TITLE
barrier=kerb should also be possible for nodes

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#252]
See [https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dkerb](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dkerb).

**Comment by simonpoole** [comment]
I don't believe the wiki is in any way consistent her and that this in fact shouldn't be allowed, but in any case https://github.com/simonpoole/beautified-JOSM-preset/commit/9030cff40791192fa40245d605b906ce3aba7b90

**Comment by jajajaneeneenee** [comment]
> I don't believe the wiki is in any way consistent

That's a quite hard judgment ... perhaps it's not 100% consistent in every detail, but it becomes better and better and it's the right place to discuss and decide, describe and document a good (or possible) use of keys and values. But it will always be a work in progress of course. And from the viewpoint of coding it may be not consistent enough, that's quite clear ...

In this case: I think it has good reasons to allow barrier=kerb on nodes (specially nodes of footways, surely not for single, unconnected nodes), and regarding disabled people (mapping for the blind). For me it makes sense to put nodes on footways at the position of a kerb (in combination of possibly missing or present tactile_paving). It is described quite good in the wiki, but perhaps still quite new and not very common (?).

A quite good illustration for crossings with barrier=kerb, kerb=* and tactile_paving=* on nodes can be found here:
[https://wiki.openstreetmap.org/wiki/Key:crossing#Additional_tags](https://wiki.openstreetmap.org/wiki/Key:crossing#Additional_tags)

**Comment by simonpoole** [comment]
> In this case: I think it has good reasons to allow barrier=kerb on nodes (specially nodes of footways, surely not for single, unconnected nodes), and regarding disabled people (mapping for the blind). For me it makes sense to put nodes on footways at the position of a kerb (in combination of possibly missing or present tactile_paving). It is described quite good in the wiki, but perhaps still quite new and not very common (?).

But that is what kerb=* is for on way nodes. As said the wiki is contradicting itself.

**Comment by jajajaneeneenee** [comment]
I would say: kerb=* is a subkey of barrier=kerb. What is contradicting?

**Comment by simonpoole** [comment]
"See also kerb=*, which is used on the node of a way at the location of the kerb. "
