### ISSUE TITLE
man_made=bridge should not get bridge=yes as a default value

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#253]
"default=yes" is defined as a default value in chunk id="bridge_details", which is used for man_made=bridge, but this results in an (low level) Osmose validation error or warning (something like _"bad combination of values – man_made=bridge together with bridge=yes"_).

I guess, only a more specific value for bridge=* should be used here, and bridge=yes is not really neccessary for man_made=bridge.

**Comment by simonpoole** [comment]
Fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/8cb56531d1796a0925203ded66fa632fa35e5531
