### ISSUE TITLE
small errors in comments

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#255]
- [ ] <item name="Gas" has comment `<!-- Hardware -->` at the end (by the way, it perhaps should better be called "Gas Shop" to prevent confusion with gas power items, e.g. after searches with the word "gas")
- [ ] <item name="Toy library" => "`<!-- Tpy library -->`"

**Comment by simonpoole** [comment]
Fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/2207775c1019d7d716043c92e0b4417a90fe0d39
