### ISSUE TITLE
item “Platform” has some small problems (e.g. two doubled keys)

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#256]
Perhaps this is concerning Vespucci only, I am not sure (I didn't try in JOSM):

I think, that these two checkboxes are never shown (in the form based tag editor of Vespucci), because the two keys ”highway“ and ”railway“ are already used some lines earlier in the same item, so they are doubled in the item:

`<check key="highway" value_on="platform" text="Highway platform (legacy)"/>`
`<check key="railway" value_on="platform" text="Railway platform (legacy)"/>`

The two other lines with ”highway“ and ”railway“ (which come first) are: 
`<check key="highway" value_on="bus_stop" text="Bus stop" disable_off="true"/>`
`<check key="railway" value_on="tram_stop" text="Tram stop" disable_off="true"/>`

If I am not concluding in a wrong way, a field (a key) in an item is displayed only maximum one time in Vespucci (the same in JOSM? I didn't check it.).

And other small issues (or questions) with this item:
- [ ]  At the end are the psv type checkboxes (bus, tram, train, ...) and everything has `disable_off="true"`, except ”share_taxi“. I don't know if this is intended.
- [ ] text="funicular", text="aerialway", text="ferry" should start with an uppercase letter: text="Funicular", text="Aerialway", text="Ferry"

**Comment by simonpoole** [comment]
The doubling definitely doesn't make sense as even if the fields were displayed it would be undefined which tag would actually be used if two with the same key are selected.

**Comment by simonpoole** [comment]
Fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/f5635f1ed8ae44240e058c99ba9928b9635247e9
