### ISSUE TITLE
Place of different Hungarian tags

### ISSUE THREAD

**Issue by debyos** [simonpoole/beautified-JOSM-preset#260]
There are two different "Method" tag translations. One for power generation and another for surveillance.

At the surveillance presets the Method for power generation appears (see image belos) and vice versa (i.e. at power generators the method for surveillance).
Please cross-change them to the other Method.

Thanks

![2021-01-24 11 06 56](https://user-images.githubusercontent.com/26843901/115971337-28764500-a548-11eb-8d62-016a927cc70c.jpg)

**Comment by simonpoole** [comment]
https://github.com/simonpoole/beautified-JOSM-preset/commit/8e76eb25b4883290c52242eae84e48d5b4a7ae0a adds translations context for "Method"
