### ISSUE TITLE
Interchanged translated tags

### ISSUE THREAD

**Issue by debyos** [simonpoole/beautified-JOSM-preset#261]
The same problem as for issue #260 

There are two types of `Lighting`:
- one for `tower:type` and 
- another one for `shop`

Now, they are confused, at least in the Hungarian version: please replace them with each other. Thanks!

**Comment by simonpoole** [comment]
Translation context for both tags exist you simply need to change them around in transifex.

**Comment by debyos** [comment]
On [Transifex](https://www.transifex.com/openstreetmap/presets/translate/#hu/presetpot/316208956?q=text%3Alighting) and also in [the code](https://github.com/MarcusWolschon/osmeditor4android/blob/15.2-MAINT/src/main/assets/preset_hu.po) they are fine. 

Just in the Vespucci app they seem to be changed.
