### ISSUE TITLE
Complaints about missing ref (guideposts) should be supressesed by noref=yes tag

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#264]
To reproduce: created guidepost node, tag with name, tag with `noref=yes`

Vespucci complains about missing ref.

https://wiki.openstreetmap.org/wiki/Key:noref

https://www.openstreetmap.org/node/2606373914
![IMG_20210505_075938](https://user-images.githubusercontent.com/899988/117129677-468d4200-ad9f-11eb-857a-eaf913777422.jpg)

**Comment by simonpoole** [comment]
Wrong repo, as is obvious from the contents of the issue. Pls move.
