### ISSUE TITLE
Presets only in iD

### ISSUE THREAD

**Issue by simonpoole** [simonpoole/beautified-JOSM-preset#27]
Presets present only in iD, ordered by count in OSM database, bold == count less than 1'000, only for amenity, shop, man_made, highway, waterway, railway, historic, tourism, emergency, leisure, aeroway (none missing), aerialway (none missing), natural (none missing), landuse, office and craft. This only takes "primary" keys in to account, further differing attributes are ignored for now.

Note: this is not a diff, there are presets missing in iD that are present here (but not as many).

Stroked through values are deprecated in iD and should likely be so here to.

**amenity**
- [x] ~~amenity=swimming_pool~~ _ignored_
- [x] amenity=public_bookcase
- [x] amenity=dojo
- [x] amenity=boat_rental
- [x] amenity=animal_shelter
- [x] amenity=public_bath
- [x] ~~amenity=register_office~~ _ignored_
- [x] amenity=animal_boarding
- [x] **amenity=crematorium**
- [x] amenity=love_hotel
- [x] amenity=waste_transfer_station
- [x] ~~amenity=coworking_space~~ _iD has replaced this with office=coworking which is however lower use and contrary to the current consensus, ignored_
- [x] amenity=animal_breeding
- [x] amenity=monastery
- [x] amenity=planetarium
- [ ] ~~amenity=scrapyard~~ _iD replaced this recently with industrial=scrap_yard (exists as value in this preset) based on a bogus wiki page_
- [x] amenity=car_pooling

**shop**
- [x] ~~shop=vacant~~ _ignored_
- [x] shop=massage
- [x] shop=second_hand
- [x] shop=trade
- [x] shop=fashion _added as deprecated_
- [x] shop=charity
- [x] shop=craft _this is very confusingly named_
- [x] shop=gas
- [x] shop=carpet
- [x] shop=bathroom_furnishing
- [x] shop=money_lender
- [x] ~~shop=fishmonger~~ _ignored_
- [x] shop=chocolate
- [x] shop=storage_rental
- [x] shop=herbalist
- [x] shop=radiotechnics
- [x] shop=e-cigarette
- [x] **shop=scuba_diving**
- [x] shop=leather
- [x] shop=tiles
- [x] shop=religion
- [x] shop=nutrition_supplements
- [x] shop=wholesale
- [x] shop=appliance _this would seem to have an odd neither deprecated nor documented state_
- [x] shop=weapons
- [x] shop=agrarian
- [x] shop=furnace _added as deprecated, use shop=fireplace instead_
- [x] shop=window_blind
- [x] shop=pyrotechnics
- [x] shop=anime
- [x] shop=water_sports _no wiki entry_
- [x] shop=candles

**man_made**
- [x] man_made=petroleum_well 
- [x] man_made=mast
- [x] man_made=pumping_station

**highway**
- [x] highway=corridor

**waterway**
- [x] **waterway=sanitary_dump_station**
- [x] waterway=water_point

**railway**
- [x] railway=derail

**historic**
- [x] historic=tomb

**tourism**
- [x] tourism=gallery
- [x] **tourism=aquarium**

**emergency**
- [x] emergency=life_ring

**leisure**
- [x] leisure=resort
- [x] leisure=dance
- [x] leisure=adult_gaming_centre
- [x] leisure=outdoor_seating
- [x] leisure=bowling_alley
- [x] leisure=amusement_arcade
- [x] leisure=hackerspace

**landuse**
- [ ] landuse=churchyard
- [ ] **landuse=harbour**

**office**
- [x] office=coworking _use amenity=coworking_space, ignored_

**craft**
- [x] craft=electronics_repair _changed craft=electronics to this_
- [x] craft=sculpter _this is a typo in the preset in iD should be sculptor, ignored_

**Present in both but deprecated in iD**
- [x] amenity=nursing_home _deprecated here too_

**Comment by bhousel** [comment]
Hey @simonpoole!  You may want to filter out the presets where `"searchable": false`.  These are ones that we don't let people actually pick in iD, but we do recognize so we can render legacy data correctly.

There are a bunch in this list - off the top of my head `shop=fishmonger`, `shop=vacant` are like this.

We also name the preset definition file with an underscore like `_fishmonger.json` or `_vacant.json`, as a  naming convention to know that it's not a searchable preset.

**Comment by simonpoole** [comment]
Hi @bhousel this is/was just a raw list semi-manually generated from the  taginfo project stats and needs to be pruned down to remove deprecated stuff and so on. Or with other words: I'm not saying that all of the preset -should- actually be included elsewhere .

Note on the side: went out survey for a bit just before and would have actually needed 3-4 shops from the list :-).

**Comment by bhousel** [comment]
> Hi @bhousel this is/was just a raw list semi-manually generated from the taginfo project stats and needs to be pruned down to remove deprecated stuff and so on

Oh that makes sense.  I wonder if iD should maybe not send the deprecated presets to taginfo in the project file?  I wouldn't want people to draw a wrong conclusion about how we use the tag, e.g. "can't deprecate `shop=fishmonger` because iD still uses it."

cc @joto ?

**Comment by joto** [comment]
@bhousel I have thought about that, too. I think it could make sense to "flag" tags in some way to make this clear. But currently there is no way of doing this. A workaround could be to have two lists, one for the used tags, one for the deprecated ones. I'd be happy for more ideas how the projects feature in taginfo can be improved, I haven't done much with it lately, because I don't see much adoption really, although I still think it is useful (as this issue shows).

**Comment by simonpoole** [comment]
@joto not sure if it is worth it, as really only the editors are likely to even have the notion of "deprecated" (well AFAIK only iD and vespucci).

Naturally it would be really nice if the comparison could be done automatically for a set of "primary keys" (open can of worms). Doesn't need a UI as such.

**Comment by joto** [comment]
@simonpoole If I remember correctly Nominatim also supports some tags that are deprecated. The meaning is slightly different there: "You should really not use this tag, but we understand it anyway." Or you want to say something like: I support `key=*`, but not `key=special_value`. There is no way to express this. So there are more reasons to have some some "flags" on tags. I am just not sure how to do this without making everything too complicated.

**Comment by matkoniecz** [comment]
>  amenity=register_office should be deprecated in iD see the wiki

Is the need for deprecation reported somewhere? Because according to https://github.com/openstreetmap/iD/issues/3245 it already got deprecated one year ago.

**Comment by matkoniecz** [comment]
> amenity=scrapyard

now deprecated in iD - see https://github.com/openstreetmap/iD/commit/9c5a79a714e9a8cc34515f241d052a728908a29b

**Comment by matkoniecz** [comment]
> amenity=planetarium

Would be OK to make PR that would add this, without an icon?

**Comment by simonpoole** [comment]
@matkoniecz planetarium: sure, but the actual work is creating an icon.

WRT to scrapyard, unluckily the iD change https://github.com/openstreetmap/iD/commit/9c5a79a714e9a8cc34515f241d052a728908a29b doesn't actually make any sense see https://taginfo.openstreetmap.org/search?q=scrapyard#values and is another of the unilateral "trying to get my way" changes that we see do often in the iD presets.

**Comment by matkoniecz** [comment]
> the actual work is creating an icon

I know that it is 98% of work but I was unsure whatever PR with other 2% of work would be considered as useful or not.

**Comment by bhousel** [comment]
> WRT to scrapyard, unluckily the iD change openstreetmap/iD@9c5a79a doesn't actually make any sense see https://taginfo.openstreetmap.org/search?q=scrapyard#values and is another of the unilateral "trying to get my way" changes that we see so often in the iD presets (a publicly accessible scrapyard may have its landuse mapped as landuse=industrial, industrial=scrapyard, but that doesn't imply that something just mapped as landuse it is a facility you can actually use). .

I made this change for a few reasons
- The [wiki](https://wiki.openstreetmap.org/wiki/Tag:industrial%3Dscrap_yard) has some strong language that it should be tagged this way, and not as an amenity.
- It has around 200 uses worldwide, which is another way of saying - _nobody cares_.

Please be nice.  I'm not "trying to get my way", I'm just trying to close issues.  

I agree that tagging POI style features as `landuse=*` is stupid.  That ship has sailed and OSM has lots of them now.

**Comment by simonpoole** [comment]
@bhousel " "trying to get my way"  was intended for the people manipulating thing so they seem legit, in this case the creator and sole editor of the industrial=scrapyard page. 

There is a reason that historically editor presets have had a high hysteresis

**Comment by yvecai** [comment]
"I agree that tagging POI style features as landuse=* is stupid. That ship has sailed and OSM has lots of them now." 
OSM has plenty of *both*, and the ship sails well enough with that.

**Comment by simonpoole** [comment]
With exception of the landuse tags this has been done.
