### ISSUE TITLE
Allow highway=footway on closed untagged way

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#273]
To reproduce: create linear closed way (for example roundabout-like footway on a playground)

Try to tag it

Discover that footway is not available in presets

Migrated from https://github.com/MarcusWolschon/osmeditor4android/issues/1424

**Comment by simonpoole** [comment]
Changed in https://github.com/simonpoole/beautified-JOSM-preset/commit/ff301f506794830c9df4d7bca1b27d9d2c5c5b52
