### ISSUE TITLE
"Minature railway"?

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#275]
While translating presets into Polish I encountered "Minature railway" - it should be "Miniature railway", right?

**Comment by simonpoole** [comment]
Fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/c7d2e52faba1f44d2a51fe7b03ec0309daa0676d 2.10.1 

Seems as this was originally wrong in the wiki and likely wrong in the JOSM presets when we forked them.

Thanks for noticing.
