### ISSUE TITLE
Don't show `name` field for `water=river|stream` and `waterway=riverbank`

### ISSUE THREAD

**Issue by Dimitar5555** [simonpoole/beautified-JOSM-preset#279]
Currently Vespucci suggests adding a name field (https://imgur.com/a/Xn1vxVC) for objects tagged with `water=river|stream`. It should not suggest it since these areas are not supposed to have names. It is possible for it to also suggest adding a name for `waterway=riverbank` which is not right.

**Comment by matkoniecz** [comment]
See also #85

**Comment by Dimitar5555** [comment]
Reservoirs are a diffrent case. In most cases they have a dam in order to supply water or to generate electricity. Here I'm talking about river and stream areas.

**Comment by simonpoole** [comment]
There's no real good solution for this, mainly because water mapping is screwed up in general, but https://github.com/simonpoole/beautified-JOSM-preset/commit/9570738a8480962ac331c6c3b5c352f4a78c7326 addresses this a bit by moving lake, lagoon and pond to their own presets.
