### ISSUE TITLE
Uncommon value "right;through" for turn:lanes (instead of "through;right")

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#280]
When I recently tagged some road markings (turn:lanes) in Vespucci, I was very surprised that I couldn't find the value "through;right" – instead there is "right;through" which doesn't feel quite good (although it may be logically correct, too, because the order of values doesn't matter – not sure ...).

It concerns this road marking:
![road marking](https://wiki.openstreetmap.org/w/images/thumb/d/d4/Turn-through-right.png/100px-Turn-through-right.png)

### Summary
The very uncommon value combination "right;through" is used instead of the far more common "through;right" in the items "Single direction roads" and "Bi-directional roads".

I would recommend to change the lines (3 times):
` <list_entry value="right;through" short_description="Right and through"/>`

To:
` <list_entry value="through;right" short_description="Through and right"/>`

### See also table of some distribution examples here:

[https://wiki.openstreetmap.org/wiki/Talk:Key:turn#Values_for_tagging_of_left_turn_.26_through_.28only.29_and_through_.26_right_turn_.28only.29](https://wiki.openstreetmap.org/wiki/Talk:Key:turn#Values_for_tagging_of_left_turn_.26_through_.28only.29_and_through_.26_right_turn_.28only.29)

**Comment by simonpoole** [comment]
Changed in https://github.com/simonpoole/beautified-JOSM-preset/commit/75a76f08eaab5f9f7b72656cb1cc404b9e4e278d
