### ISSUE TITLE
Check key “indoor“ of the “Emergency Phone“ items needs a match="none" (at least for Vespucci)

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#289]
This issue perhaps only concerns the use of the preset in Vespucci ... I'm not sure. Didn't check in JOSM.

### The problem
My suspicion: Because "indoor" is in the list of object keys, every node which is only tagged with `indoor=yes` (and does'nt match any other item with a fixed key-value) matches with the item “Emergency Phone“, because the “Emergency Phone“ items has the code line:

`<check key="indoor" text="Indoor"/>` (without `match="none"`)

E.g. – incorrect tagged interior doors (at least according to the Simple Indoor Tagging scheme) like ...
```
door=hinged
indoor=yes
```
... are displayed on the map in Vespucci with the red “Emergency Phone“ icon (SOS!). Or any node which only has `indoor=yes` matches with the “Emergency Phone“ item.

In other items which have a indoor check field, there is a match="none" parameter OR it is part of an `<optional>` block. E.g.: Automated Defibrillator, First Aid Kit, Elevator.

And also a `disable_off="true" `would make sense, I think.

### And two questions regarding the matching systematics in Vespucci (which is linked with this issue):

1. It seems that every check/combo/multiselect key matches, if key and value matches and if the key is an "object key" – hardwired (see [https://github.com/MarcusWolschon/osmeditor4android/blob/master/src/main/java/de/blau/android/osm/Tags.java#L429](https://github.com/MarcusWolschon/osmeditor4android/blob/master/src/main/java/de/blau/android/osm/Tags.java#L429) – IMPORTANT_TAGS set) or defined in the object_keys of the preset xml (value="yes" matches for a check field and any single value which is in the list of values matches for a combo/multiselect field) – **even if there is no match="keyvalue" parameter**. Is this the standard matching behaviour in Vespucci? – So it means, that `match="keyvalue"` has the same effect than no "match" parameter?
2. There is never a matching if such a field (key) is in an `<optional>` block?

**Comment by simonpoole** [comment]
1, yes
2. yes

As you say the problem is that indoor is a top level key and an attribute at the same time (not the only tag that has this issue), the fix is as you say to add a match="none" to the tag.

**Comment by jajajaneeneenee** [comment]
Thank you for the information.

And perhaps you could add the information to the preset tutorial page ([http://vespucci.io/tutorials/presets/](http://vespucci.io/tutorials/presets/)), that the default matching process for check/combo/multiselect is equivalent to  `match="keyvalue"` (if no match parameter is used). Something like:

`match | supported (default behaviour for no value is equivalent to match="keyvalue")`

At least for me, it would make things clearer, specially because the whole matching system is not easy to understand in every detail. This would lift the fog a little.
