### ISSUE TITLE
Trying to create my own preset

### ISSUE THREAD

**Issue by duiveldoder** [simonpoole/beautified-JOSM-preset#294]
I created a very simple xml - JOSM imports it without a hassle and it works 100% as intended.

I import it to the Vespucci and I get a "element not found" error message.

Then I stripped it to the absolute basics - still get the "element not found" error message.

This is the actual stripped down file:

<?xml version="1.0"?>
<presets xmlns="http://josm.openstreetmap.de/tagging-preset-1.0" shortdescription="Addresses Baguio" description="Adding Addresses to Baguio City">
	<group name="addresses">
		<item name="building" type="node,closedway,multipolygon">
			<text key="addr:housenumber" text="House number" default="" />
		</item>
	</group>
</presets>

Would anyone be so kind to explain me what's wrong with this basic file - why vespucci claims it's wrong without actually telling me what's wrong with it?

Kind regards

**Comment by simonpoole** [comment]
@duiveldoder your file didn't get included, you will likely need to change the file extension to .txt

**Comment by duiveldoder** [comment]
`<?xml version="1.0"?>
<presets xmlns="http://josm.openstreetmap.de/tagging-preset-1.0" shortdescription="Addresses Baguio" description="Adding Addresses to Baguio City">
	<group name="addresses">
		<item name="building" type="node,closedway,multipolygon">
			<text key="addr:housenumber" text="House number" default="" />
		</item>
	</group>
</presets>`

Hope it now uploads the actual text/xml

android 10 - Vespucci 15.2.8

**Comment by simonpoole** [comment]
Works as expected for me. Are you perhaps trying to load the file as OSM data? That is not going to work.

**Comment by duiveldoder** [comment]
> me. Are you perhaps trying to load the file as OSM data

I copied the xml file directly to my phone and then use the "add JOSM compatible preset" clicking on the little SD card symbol to import the file directly

**Comment by duiveldoder** [comment]
Also tried files from https://josm.openstreetmap.de/wiki/Presets

they all give the same error message "element not found"

Add preset will add a new preset, you will need to supply an URL for the file containing the preset and a name or select a preset file (click the SD-card icon) that is available on your device. Vespucci will download the preset and any icons referenced by URL in the file, presets contained in a ZIP-archive are supported too. (requires network connectivity for downloading)

And this is what I'm doing - that gives me that error message of "element not found"

**Comment by simonpoole** [comment]
As you are on Android 10: are you sure that you have read access to the location you copied the file to? Maybe a short video of the process would be helpful, as this is decidedly weird.

**Comment by matkoniecz** [comment]
@duiveldoder For video capture Ez Screen Corder seems fine and I used it in past (though let me know if that app is stealing data or something)

**Comment by simonpoole** [comment]
A couple of screenshots are naturally OK too (particularly of the error message).

**Comment by duiveldoder** [comment]
Sorry for late reply - food poisoning struck me down for a bit..

anyway these are the permission settings for the app
![Screenshot_20211204_064120_com google android permissioncontroller](https://user-images.githubusercontent.com/15773876/144682727-11e4dc64-74d6-4289-afa8-9402c18a61d3.jpg)

The following screenshots show what I do - hopefully uploaded synchronically
![Screenshot_20211204_064234](https://user-images.githubusercontent.com/15773876/144682751-f7bc2fcf-6e14-4b53-975c-1a5bef402ced.jpg)
![Screenshot_20211204_064243](https://user-images.githubusercontent.com/15773876/144682762-9309531f-375c-4844-95df-cc7566641c3c.jpg)
![Screenshot_20211204_064253](https://user-images.githubusercontent.com/15773876/144682770-e2cdbf06-633c-49b3-b9b6-4cbdf18fdd76.jpg)
![Screenshot_20211204_064257_de blau android_edit_195195343588441](https://user-images.githubusercontent.com/15773876/144682772-e4cd3446-ec7f-408d-b424-c8ebbbf7fc77.jpg)
![Screenshot_20211204_064357](https://user-images.githubusercontent.com/15773876/144682779-083aba34-98a2-4cac-bec2-37466a98d512.jpg)
this is a file I downloaded straight from the wiki osm webpage - same error as my own file.
![Screenshot_20211204_064404_com android documentsui_edit_195255424133744](https://user-images.githubusercontent.com/15773876/144682780-603b1c0e-83ec-466d-8cad-bd56868a5205.jpg)
![Screenshot_20211204_064441_de blau android](https://user-images.githubusercontent.com/15773876/144682783-dc74760d-476d-4832-b8ed-f6a51440968f.jpg)

**Comment by simonpoole** [comment]
I hope you are feeling better now.

The error happens way before the preset file is parsed or before it is even configured. At the back of my head I believe there might have been an issue with accessing preset files from the Download directory (SAF related), but I haven't been able to put my finger on it just yet. In any case you should try moving the file to the Vespucci director and re-try. 

Unluckily you are a couple of versions behind so it's a bit of a pain trying to dissect this, in particular the error message.

**Comment by duiveldoder** [comment]
Yes - moving it to the Vespucci folder works. Thank you.

But what do you mean a few versions behind? I always have latest version from F-Droid. F-Droid not supported anymore?

**Comment by simonpoole** [comment]
> But what do you mean a few versions behind? I always have latest version from F-Droid. F-Droid not supported anymore?

That is not the correct way to frame it. 

F-Droid takes open source projects, builds them and distributes the generated APKs themselves. Nothing against that, it is open source software, however F-Droid is 100% responsible for what it does and currently they have broken something and it is totally outside of our control if and when they might or might not fix it (note that we have built the versions after 15.2.8 literally 100s if not 1000s of times). Again, to be clear: we have -ZERO- control over what they do or don't do.

Your best bet if you, understandably, don't want to get the APK from the google play store, is to use the APKs from the release section on this repo. These are identical to the versions google distribute and have been signed with the same key.
