### ISSUE TITLE
Split 'game'

### ISSUE THREAD

**Issue by debyos** [simonpoole/beautified-JOSM-preset#298]
Dear All,

in the presets `game` ([in the Hungarian file at line 4805](https://github.com/simonpoole/beautified-JOSM-preset/blob/master/i18n/preset_hu.po)) should be split in two:
- one for the food to buy at a butcher and
- another for the clubs
Thanks

Gábor

**Comment by simonpoole** [comment]
Thanks for the report.

Fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/ca565e9013e265af4ddd338011e59962da23caea
