### ISSUE TITLE
Tag:service=parking

### ISSUE THREAD

**Issue by Davileci** [simonpoole/beautified-JOSM-preset#299]
Deprecated preset:
Service way type=Estacionamiento (spanish)

https://wiki.openstreetmap.org/wiki/Tag:service%3Dparking_aisle#Possible_Tagging_Mistakes

**Comment by simonpoole** [comment]
Addressed in https://github.com/simonpoole/beautified-JOSM-preset/commit/469502f5208a01f9e78ba1fa41750d3390cd97ff
