### ISSUE TITLE
craft=floorer

### ISSUE THREAD

**Issue by datendelphin** [simonpoole/beautified-JOSM-preset#3]
preset for craft=floorer. Floorer does both which a carpet_layer or parquet_layer does. See https://wiki.openstreetmap.org/wiki/Tag:craft%3Dfloorer

**Comment by simonpoole** [comment]
https://github.com/simonpoole/beautified-JOSM-preset/commit/73e5a2085087d3d3b53a7656de26504bbfed7fb4 note icon missing
