### ISSUE TITLE
 poor Polish translation, makes adding objects under construction complicated in Vespucci

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#30]
Reproduced with inexperienced person attempting to add landuse=construction

Vespucci followed system language (without override) and switched to Polish.

Searching "budowa" displayed confusingly titled craft=construction and highway=construction but not landuse=construction.

Neither highway=construction nor craft=construction was recognizable from title and icon. Landuse=construction was not found. It seems that switch to English is unavailable.

**Comment by simonpoole** [comment]
In principle the original English is always added to the search index. But in any case if it is a translation issue, you should be able to see and fix it on transifex.

**Comment by matkoniecz** [comment]
> you should be able to see and fix it on transifex

How can I locate and improve translation for road under construction? I managed to locate using search entry for landuse=construction, but I was unable to locate translation of highway=construction

**Comment by simonpoole** [comment]
This issue with "construction" is that it didn't have separate translation contexts for the use as a landuse, highway and craft value (you can see where the specific entry is being used under "More info", Occurrences") in English this works but doesn't in some other (including German). I added the additional contexts now so you should be able to add separate translations.

**Comment by matkoniecz** [comment]
@simonpoole Thanks! I improved translations, but there is still problem with craft=construction

It is nearly unused (101 instances worldwide https://taginfo.openstreetmap.org/search?q=craft%3Dconstruction ) and undocumented at http://wiki.openstreetmap.org/wiki/Key:craft

At this moment I have no idea how it is supposed to be translated - I am unable to guess its meaning. Is it place where unspecified things are constructed? Or place to make tools to construct other things?

I propose to remove it from preset as confusing and not established tag or, if this tag should be promoted, add documentation on OSM wiki.

**Comment by simonpoole** [comment]
I expect that is is essentially a synonym for craft=builder ... removing it is a good idea.

**Comment by matkoniecz** [comment]
Is it also something that should be done upstream in JOSM?

**Comment by simonpoole** [comment]
No, JOSM didn't have any craft and office presets at all when I forked this.

**Comment by simonpoole** [comment]
craft=construction removed in https://github.com/simonpoole/beautified-JOSM-preset/commit/b852be3264e143c553ce591791233608258f0503

**Comment by simonpoole** [comment]
I suspect a week or two to the monthly release update.

**Comment by matkoniecz** [comment]
I checked it again and now it works! Thanks!
