### ISSUE TITLE
Item “Utility pole” - is a fixed tag (man_made=utility_pole) missing? And is it really deprecated?

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#300]
Isn't the fixed tag "man_made=utility_pole" missing in the item? (release 3.4.2)

        <item name="Utility pole" icon="man_made_pole.png" type="node" preset_name_label="true" deprecated="true">
            <link wiki="Tag:man_made=utility_pole"/>
            <space />
            <reference ref="pole" />
            <reference ref="utilities" />
            <preset_link preset_name="Pole" text="Similar preset:" alternative="true" />
        </item> 

And I'm not 100% sure, but is it really a deprecated tag (the item has deprecated="true")? I never used it so far, but the [Wiki page](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dutility_pole) says "Status=approved" and >66k uses.

See also #35 – there it is checked.

Other small thing: in `<chunk id="utilities">`, which is also used for the item "Marker", the value "hydrant" is missing (this seems to be used for markers, but only 142 uses ...). And it doesn't really fit to the item "Utility pole" or "Mast", where "utilities" is also referenced ... perhaps a new chunk for "Marker" would be necessary (?).

**Comment by simonpoole** [comment]
Fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/ff7a777d0fbc54abf3c3b03ab173f751ed8ccc98

The "deprecated" is because the item was added a lot before there was any vote on it, and it was unclear if it would ever be approved.
