### ISSUE TITLE
Deprecate vending=parcel_pickup

### ISSUE THREAD

**Issue by overflorian** [simonpoole/beautified-JOSM-preset#301]
Hi,
A new tag just [has been approved](https://wiki.openstreetmap.org/wiki/Proposed_features/amenity%3Dparcel_locker): [amenity=parcel_locker](https://wiki.openstreetmap.org/wiki/Proposed_features/amenity%3Dparcel_locker) and describes a parcel locker.
It replaces previously used (and now deprecated) amenity=vending_machine + vending=parcel_pickup

I propose to:
1. While a amenity=vending_machine is created, stop proposing the associated preset vending=parcel_pickup
2. Create a new dedicated preset for amenity=parcel_locker

Thanks

PS: deprecation follow-up (including similar requests to other tools) is available on this wiki page: https://wiki.openstreetmap.org/wiki/Tag:vending%3Dparcel_pickup#Deprecation_follow-up

**Comment by Sarabjeet108** [comment]
I believe that the tag vending=parcel_pickup is yet to be added. Can I work on this issue?

Also, will _deprecated="true"_ work fine to stop thr deprecated tag  _vending=parcel_pickup_ from being proposed
