### ISSUE TITLE
Double values in multiselect key of chunk id="sport"

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#302]
### Preset version ###
v3.4.3

### Issue ###
Perhaps this will not result in an error, but these values are double in the multiselect key="sport" (I just came across it by accident):

```
ice_skating
9pin
10pin
```

Perhaps one should always sort such lists of values alphabetically, then it is less likely to insert duplicate values.

**Comment by simonpoole** [comment]
Fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/03a03eb3d4025203b2ce5621cc145c15fc4007f7
