### ISSUE TITLE
Translation too broad for outdoor

### ISSUE THREAD

**Issue by HolgerJeromin** [simonpoole/beautified-JOSM-preset#303]
I see in translate site for outdoor:

Occurrences

master_preset.xml:2450(combo:display_values|preset:Elevator|key:surveillance):, master_preset.xml:8609(combo:display_values|group:Man_Made|preset:Surveillance|key:surveillance):, master_preset.xml:9823(item:name|group:Clothes|preset:Outdoor):

Only "power" is separated.

ref https://github.com/MarcusWolschon/osmeditor4android/issues/1558

**Comment by simonpoole** [comment]
I suppose only the clothes version really needs a translation context?
