### ISSUE TITLE
emergency_ward_entrance: disallow entrance=emergency

### ISSUE THREAD

**Issue by pippopip** [simonpoole/beautified-JOSM-preset#306]
[This commit](https://github.com/simonpoole/beautified-JOSM-preset/commit/9ee601f8716a14441a57fc4929df3df5f86e4c11) adds `entrance=emergency` to the preset of `emergency=emergency_ward_entrance`.

However [the wiki](https://wiki.openstreetmap.org/wiki/Tag:emergency=emergency_ward_entrance) mentions that `entrance=emergency` is unrelated (`an emergency exit to escape a building in case of fire`), so it should not be used in connection with `emergency_ward_entrance`, which is a place where injured people seek medical help.

**Comment by simonpoole** [comment]
There is no reason that theFixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/9b477466c2f9708661e27ba72d2c87d2beb7cb68 entrance to
