### ISSUE TITLE
Tagging of sidewalk:surface v sidewalk:both:surface

### ISSUE THREAD

**Issue by davidpnewton** [simonpoole/beautified-JOSM-preset#309]
In the recent update to the tagging for highway pavements (sidewalks) the tagging of sidewalk:surface=xxx was introduced to represent situations where a pavement on both sides of the road has the same surface, so sidewalk:surface=asphalt for example. However this appears to conflict with the alternative tagging of sidewalk:both:surface=xxx.

At the moment neither are supported in the standard JOSM preset nor in iD. Vespucci has recently started supporting sidewalk:surface of course with the update of this preset. However there's another editor that has also made a recent tagging change of this nature which conflicts with Vespucci: Streetcomplete. One of Streetcomplete's new tasks is tagging of surfaces of pavements indicated by sidewalk=left/right/both. However it is using the sidewalk:both:surface tagging paradigm rather than sidewalk:surface.

Looking at Taginfo it appears that the Vespucci tagging scheme has about 6,500 instances whilst the Streetcomplete tagging scheme has about 20,000 instances.

Please consider changing the Vespucci preset from sidewalk:surface to sidewalk:both:surface to be compatible with Streetcomplete and to reflect the tag in more common use in the database by a factor of over 3 times.

**Comment by simonpoole** [comment]
I don't see were the conflict is, sidewalk:surface and sidewalk:both:surface are simply synonyms there is no semantic difference but the former fits better to the "simple" sidewalk tagging scheme sidewalk with 2.6 million uses.

Naturally SC needs to respect this tagging and only change it when it is really necessary, anything else is a mechanical edit and should stop (but it wouldn't be the first time this has happened).

**Comment by davidpnewton** [comment]
You don't see where the conflict is. They are different tags for the same thing. It is comparatively early in their adoption in the system and you have chosen to support the less popular (by a factor of 3) one.

The mere fact that they are different tagging schemes for the same thing is the conflict. The fact that there is no semantic difference but that they are incompatible is the conflict.

Do you suggest that they be tagged with both schemes? That is of course one possible solution. I have adopted that one myself to some degree when tagging both lanes=x and lanes:forward=x for a way where oneway=yes is also present. It's also present to some degree with traffic_sign and traffic_sign:2 v traffic_sign:forward and traffic_sign:backward. I know that validators (Osmose for example) throw error messages when both lanes and lanes:forward tagging is present on oneway ways. So perhaps, by extension, Osmose should throw an error if sidewalk:surface is present alongside sidewalk:both:surface on the same way. Which should win then? Which should be eliminated to remove duplication of tagging? Taginfo says sidewalk:surface should lose and be eliminated based on much lower usage. 

I am trying to head off two different tags being supported by different editors and the difference growing and growing. So far JOSM and iD haven't taken a side in this from a default preset point of view. Particularly when iD takes a side (if it ever does) that will essentially de facto decide things.
