### ISSUE TITLE
add toilets:access

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#31]
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets

**Comment by simonpoole** [comment]
toilets:access is for use with toilets=yes/no on buildings or similar (amenities?). Either the tags should be added as optional tags for such objects or we need a utility preset for this.

**Comment by matkoniecz** [comment]
It would make sense to suggest it once toilets=yes is present.

**Comment by simonpoole** [comment]
JOSM presets don't really have internal statements that can work depending on other values.

What I've done in https://github.com/simonpoole/beautified-JOSM-preset/commit/5d083f5da73c622f0322b561cd5bf5e120ac47bf is to add the appropriate tags to a larger number of facilities where you can expect at least semi-public access.

Can you have a look at http://simonpoole.github.io/beautified-JOSM-preset/ and check if that works for you?

**Comment by matkoniecz** [comment]
It seems to work, thanks!
