### ISSUE TITLE
Traffic signs

### ISSUE THREAD

**Issue by davidpnewton** [simonpoole/beautified-JOSM-preset#313]
Version 4.0.0 appears to have a regression for the Traffic Sign Backward and Traffic Sign Forward presets. Like the cycle advanced stop line was prior to this version the icon is not rendering for either preset and they are not being found as a preset when editing nodes.

**Comment by simonpoole** [comment]
With what (vespucci 17.0, 17.1, JOSM) are you seeing the behaviour? There hasn't been any relevant change to the preset itself, but traffic_sign:... is a special case (different than cycleway=asl, which btw matches now in 17.1), that may have some issues with some matching correctness fixes.

**Comment by davidpnewton** [comment]
17.1.0 beta of Vespucci.

**Comment by simonpoole** [comment]
It's a small regression wrt text fields that are used to indicate objects (I suspect traffic_sign:forward/backward is the only case), anyway it is already in the process of being fixed and will work again in the next beta.

**Comment by davidpnewton** [comment]
Hopefully this was a fairly easy fix, unlike the ASL one which did appear to be more complicated.
