### ISSUE TITLE
Club preset not recognised

### ISSUE THREAD

**Issue by davidpnewton** [simonpoole/beautified-JOSM-preset#315]
Club= is not recognised as a preset in Vespucci 17.0.1 beta and consequently isn't rendering either.

**Comment by simonpoole** [comment]
This was just a quirk in the specific item that wasn't matching on club= without any value (this is a general issue with presets like this that will need some thought in the future), once the value was set it would match.

https://github.com/simonpoole/beautified-JOSM-preset/commit/5d18d70d5a4b634e8043b6399937bc303bca539a improves the behaviour.
