### ISSUE TITLE
power=tower – deprecated (and new) tags

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#319]
In the code for `item name="Power Tower"` I saw this comment: 

`<!-- tower:type and branch:type are "deprecated" -->` (And this seems to be correct; see below)

And the tags are placed in an optional block. Perhaps they should get a `deprecated="true"` attribute?

I'm not a power tower expert, but in the english Wiki I found this information for tower:type: _"Please note that the [tower:type](https://wiki.openstreetmap.org/wiki/Key:tower:type)=* combination with [power](https://wiki.openstreetmap.org/wiki/Key:power)=tower has been discouraged and [line_attachment](https://wiki.openstreetmap.org/wiki/Key:line_attachment)=* or [line_management](https://wiki.openstreetmap.org/wiki/Key:line_management)=* are now recommended."_

And the [Wiki page for branch:type](https://wiki.openstreetmap.org/wiki/Key:branch:type) even has a stronger deprecated warning.

And of course, the newer tags [line_attachment](https://wiki.openstreetmap.org/wiki/Key:line_attachment)=* and [line_management](https://wiki.openstreetmap.org/wiki/Key:line_management)=* should then be added to the item.

**Comment by simonpoole** [comment]
Fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/6b09a4d8f76398c24f6fab744f010f0c5f3cc49e
