### ISSUE TITLE
is it OK to translate "deprecated" as "outdated"?

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#32]
In Polish there is no equivalent of "deprecated" and closest is "przestarzałe" what means "outdated".

Is it OK to use this pejorative translation?

---

There is number of terms to translate with "(deprecated)" as part ( https://www.transifex.com/openstreetmap/presets/translate/#pl/presetpot/116088711?q=deprecate )

Unfortunately in Polish there is no word equivalent to deprecated (for example http://edict.pl/dict?word=deprecated&words=&lang=EN translates deprecated as

> określenie funkcji lub programu, który staje się przestarzały i jest powoli zamieniany innym, nowszysm produktem

, printed Kościuszko Foundation Dictionary has no word "deprecated" and "deprecate" has translations for different meanings)

https://www.transifex.com/openstreetmap/id-editor/translate/#pl/presets?q=deprecate is not helpful as iD is not displaying to user whatever tag is deprecated

**Comment by simonpoole** [comment]
Sure, you should do whatever makes sense in your language (in German is is translated to "veraltet").
