### ISSUE TITLE
Alphabetizing bug (Ä is interpret as an A by the system)

### ISSUE THREAD

**Issue by vespucci-reporter** [simonpoole/beautified-JOSM-preset#329]
Description:
---

When I search for "bänk" ("bench") the system present a deluge of POIs containing the word "bank" ("bank"). This is most likely a result of that the system wrongly interpret the letter Ä as a type of A.

The app's language option is set to System Language (i.e. Swedish)

Device info:
---
<table>
<tr><td>App version</td><td>17.1.5.0</td></tr>
<tr><td>App version code</td><td>2106</td></tr>
<tr><td>Android build version</td><td>G986BXXSEFVF4</td></tr>
<tr><td>Android release version</td><td>12</td></tr>
<tr><td>Android SDK version</td><td>31</td></tr>
<tr><td>Android build ID</td><td>SP1A.210812.016.G986BXXSEFVF4</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>y2s</td></tr>
<tr><td>Device model</td><td>SM-G986B</td></tr>
<tr><td>Device product name</td><td>y2sxeea</td></tr>
<tr><td>Device hardware name</td><td>exynos990</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Christoffre"/>Christoffre</A></td></tr>
</table>

**Comment by simonpoole** [comment]
The reason for the behaviour is that all input and the strings in the search index are normalized, among other things accents and umlauts are removed. Any fix would likely need to go via scoring by comparing to the original, non-normalized, string.

I've opened an issue in the Vespucci repo https://github.com/MarcusWolschon/osmeditor4android/issues/1722
