### ISSUE TITLE
Is it necessary for bays to be large?

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#33]
> A large body of water partially enclosed by land but with a wide mouth.

http://wiki.openstreetmap.org/wiki/Tag:natural%3Dbay is not mentioning "large" size of qualifier.

It may be related to cultural differences, but I am surprised by "large" requirements (Polish Wikipedia even explicitly mentions that size of water area is in not relevant).

transifex identifier: master_preset.xml:2936(label:text|group:Water|preset:Bay):

**Comment by simonpoole** [comment]
This the original text from the JOSM preset (currently Vespucci doesn't display label elements, see http://vespucci.io/tutorials/presets/ so it doesn't matter), and should likely be changed there.

**Comment by matkoniecz** [comment]
reported upstream: https://josm.openstreetmap.de/ticket/15259#ticket

**Comment by Klumbumbus** [comment]
fixed in JOSM

**Comment by matkoniecz** [comment]
@Klumbumbus Thanks!
