### ISSUE TITLE
Etiqueta de loja de skate e de acessórios de skate

### ISSUE THREAD

**Issue by vespucci-reporter** [simonpoole/beautified-JOSM-preset#332]
Description:
---

Loja de skate e de acessórios de skate

Device info:
---
<table>
<tr><td>App version</td><td>17.1.6.0</td></tr>
<tr><td>App version code</td><td>2107</td></tr>
<tr><td>Android build version</td><td>V12.5.8.0.RGGMIXM</td></tr>
<tr><td>Android release version</td><td>11</td></tr>
<tr><td>Android SDK version</td><td>30</td></tr>
<tr><td>Android build ID</td><td>RP1A.200720.011</td></tr>
<tr><td>Device brand</td><td>Redmi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>begonia</td></tr>
<tr><td>Device model</td><td>Redmi Note 8 Pro</td></tr>
<tr><td>Device product name</td><td>begonia</td></tr>
<tr><td>Device hardware name</td><td>mt6785</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/rodriveiga10"/>rodriveiga10</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Wouldn't this be best tagged by using shop=sports and sport=skateboard ?

**Comment by simonpoole** [comment]
Closing since stale
