### ISSUE TITLE
cuisine=traditional should be minor case 

### ISSUE THREAD

**Issue by overflorian** [simonpoole/beautified-JOSM-preset#334]
Hi, 
Vespucci adds the tag cuisine=Traditional via the preset in a restaurant form.
Please change "Traditional" for "traditional" in minor case to respect the OSM format for values.

I double checked all the other "cuisine" values and found no other upper case exception.
Thanks

**Comment by simonpoole** [comment]
Hi, the thing is we don't actually have that value (at all) for cuisine, see https://github.com/simonpoole/beautified-JOSM-preset/blob/master/master_preset.xml#L556 so I'm not sure why you believe that it originated here. Do you have an example object with this tagged (or previously tagged)?

**Comment by simonpoole** [comment]
I had a quick look myself the only ones I could find had the (clearly wrong tag) added ~3 years ago. " from Go Map!! (that has in the mean time switch to iD presets I believe), and one from Osm Contributor.

**Comment by overflorian** [comment]
Hi, it's this object https://www.openstreetmap.org/node/6567824086 
You are right : it's edited by OSM Contributor so, I apologize for the incorrect request.
I think I have been led into error by the fact that Vespucci suggests already used tags on loaded data (which I think is actually a clever standard behaviour).

> Suggestion to avoid any new similar issue in the future: using JOSM/Osmose validator to be able to add a message such as "instead of cuisine=Traditional, do you mean cuisine=traditional ? That's the recommended way of mapping"
