### ISSUE TITLE
healthcare=birthing_center seems to be changed to healthcare=birthing_centre

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#339]
I’m not a healthcare tagging expert, but I saw in the Wiki that `healthcare=birthing_centre` seems to be the preferred writing now instead of `healthcare=birthing_center` (BE instead of AE).

Taginfo (2022-09-24): 
* `healthcare=birthing_centre` –> 499x
* `healthcare=birthing_center` –> 26x

Wiki pages:
* [https://wiki.openstreetmap.org/wiki/Tag:healthcare%3Dbirthing_centre](https://wiki.openstreetmap.org/wiki/Tag:healthcare%3Dbirthing_centre)
* [https://wiki.openstreetmap.org/wiki/Tag:healthcare%3Dbirthing_center](https://wiki.openstreetmap.org/wiki/Tag:healthcare%3Dbirthing_center)

That's why I would suppose to change it in item "Other healthcare facilities".

**Comment by Hufkratzer** [comment]
Related: https://github.com/openstreetmap/id-tagging-schema/issues/398

**Comment by simonpoole** [comment]
Fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/5ad9781b118502a2b5c1efc3d068157a21d7e300
