### ISSUE TITLE
provide synonyms

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#34]
In Polish "budowa" means construction, so somebody who wants to use landuse=construction may search using this word

Unfortunately, Vespucci is unable to guess that it refers to this form as to make meaning clear it is named "teren budowy".

It would be desirable to allow adding synonyms for use by search.

**Comment by simonpoole** [comment]
This is a general problem with the JOSM preset system which has been discussed there too, likely we will be implementing something on our own.

**Comment by simonpoole** [comment]
Solution for now: https://github.com/MarcusWolschon/osmeditor4android/commit/b9cf1cf6b561f9609d15ebce217ae6b4da59a912
