### ISSUE TITLE
Add opening_hours:drive_through

### ISSUE THREAD

**Issue by yaomtc** [simonpoole/beautified-JOSM-preset#347]
Have to type `opening_hours:drive_through` in Details manually. Is it possible to have that field show up for restaurants when `drive_through=yes`? Otherwise an option in the three-dot menu of the opening hours dialog might be useful, such as "add rule for..." > "Drive through". Could add `opening_hours:kitchen` there too, since it's suggested in Details.

I see that JOSM does not include opening_hours:drive_through either, not in a preset nor as an autocomplete suggestion for tags. They don't support footway=traffic_island either as it is too low of usage to be a priority

https://josm.openstreetmap.de/ticket/21912

I have a feeling if I opened a ticket there for this issue, they would probably close that one, too. 

I would fix it myself and make a pull request if I had that skill, but I'm a graphic artist, so the best I can do is make some icons

**Comment by simonpoole** [comment]
Assuming this is mainly for fast-food establishments and similar, it should simply be added to the corresponding preset items as a field, for example like opening_hours:kitchen here https://github.com/simonpoole/beautified-JOSM-preset/blob/master/master_preset.xml#L4946 but enclosed in an optional block.

**Comment by simonpoole** [comment]
> but I'm a graphic artist, so the best I can do is make some icons

BTW, we have quite a number of missing icons, and some are, lets say "suboptimal", so any help would be welcome.

**Comment by yaomtc** [comment]
@simonpoole, I made one. Haven't contributed graphics to a software project before, should I make a pull request or wait until I've made a few more?
![bus-lane2](https://user-images.githubusercontent.com/5534045/202604224-2a827387-6d04-41c5-8bf6-fb40a0542f20.svg)
![bus-lane2](https://user-images.githubusercontent.com/5534045/202604275-8ca10904-8c1a-4e82-8c81-4d480eaf9147.png)

**Comment by simonpoole** [comment]
A PR would probably be best, thanks.
