### ISSUE TITLE
Natural:Beach

### ISSUE THREAD

**Issue by vespucci-reporter** [simonpoole/beautified-JOSM-preset#352]
Description:
---

Natural:beach is a very common landmark in my country but the presets for "natural" do not show the "beach" option. Still, the app displays the beach icon after the node was created. 

Device info:
---
<table>
<tr><td>App version</td><td>18.0.5.0</td></tr>
<tr><td>App version code</td><td>2206</td></tr>
<tr><td>Android build version</td><td>G970FXXUGHVJ5</td></tr>
<tr><td>Android release version</td><td>12</td></tr>
<tr><td>Android SDK version</td><td>31</td></tr>
<tr><td>Android build ID</td><td>SP1A.210812.016.G970FXXUGHVJ5</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>beyond0</td></tr>
<tr><td>Device model</td><td>SM-G970F</td></tr>
<tr><td>Device product name</td><td>beyond0ltexx</td></tr>
<tr><td>Device hardware name</td><td>exynos9820</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Daniel BP"/>Daniel BP</A></td></tr>
</table>

**Comment by simonpoole** [comment]
This is due to the preset currently not supporting tagging on nodes, but I and the wiki agree that this should be allowed.
