### ISSUE TITLE
Chunks `link_contact_address` and `link_contact_address_payment` broken?

### ISSUE THREAD

**Issue by ltog** [simonpoole/beautified-JOSM-preset#358]
When looking at

- https://github.com/simonpoole/beautified-JOSM-preset/blob/5957ec25e9e69c40acfbd1bcb2231c8ceaff38fc/master_preset.xml#L1205-L1209
- https://github.com/simonpoole/beautified-JOSM-preset/blob/5957ec25e9e69c40acfbd1bcb2231c8ceaff38fc/master_preset.xml#L1210-L1216

we see the chunks `link_contact_address` and `link_contact_address_payment` being created.

They are used e.g. in
- `office=company` at https://github.com/simonpoole/beautified-JOSM-preset/blob/5957ec25e9e69c40acfbd1bcb2231c8ceaff38fc/master_preset.xml#L13667-L13676
- `shop=caravan` at https://github.com/simonpoole/beautified-JOSM-preset/blob/5957ec25e9e69c40acfbd1bcb2231c8ceaff38fc/master_preset.xml#L4429-L4437

However, when creating one of these places, applying the preset does add _some_ tags, but not those listed above.

Maybe the lines

- https://github.com/simonpoole/beautified-JOSM-preset/blob/5957ec25e9e69c40acfbd1bcb2231c8ceaff38fc/master_preset.xml#L1207
- https://github.com/simonpoole/beautified-JOSM-preset/blob/5957ec25e9e69c40acfbd1bcb2231c8ceaff38fc/master_preset.xml#L1212

confuse the Vespucci?

I am using Vespucci 18.1.1 but I think this has occurred already some months before.

**Comment by simonpoole** [comment]
Both chunks contain only preset links (add presets to the MRU preset item display)  and nothing that is applied automatically, so the behaviour would seem to be expected.

**Comment by ltog** [comment]
Oh, ok, I see... I didn't see/know about the MRU preset item display.

For anyone else reading, I refer to the menu on the bottom of this screen:

I guess this issue can be closed...

![image](https://user-images.githubusercontent.com/4726277/215406157-b7443ed8-fb96-408e-8325-6c12cf306c62.png)
