### ISSUE TITLE
include wetland tags

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#36]
It seems that wetland tags are missing from preset

What is surprising - searching for wetland in repository gives some limited results.

**Comment by simonpoole** [comment]
You had me stumped for a second ... but then I found the preset, for whatever reason the JOSM creators decided to put it in the Water group see http://simonpoole.github.io/beautified-JOSM-preset/#Water 

IMHO it would probably be better in "Natural" but I suppose one could argue both ways (together with the Mud preset).

**Comment by matkoniecz** [comment]
Now I am unable to reproduce my problem...

**Comment by simonpoole** [comment]
I've added some code to vespucci to add subtypes to the preset search index https://github.com/MarcusWolschon/osmeditor4android/commit/fb128de79e5d5f5b60b737a90386392e6123c8d1 before it would have only found wetland, now it finds bog, marsh etc.  or the translations. This further might fix some of the other problems you've been having with the preset search. Note: this currently will only work for subtypes that follow the schema:

main_key=type
type=sub_type
