### ISSUE TITLE
Remove all deprecated tag suggestions

### ISSUE THREAD

**Issue by jidanni** [simonpoole/beautified-JOSM-preset#372]
Here we see "official" is still suggested even though warned about on  https://wiki.openstreetmap.org/w/index.php?title=Key:access#Possible_tagging_mistakes  .
So all such deprecated tags should be removed from suggestions.

![Screenshot_20230329_205052_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/228543203-87175c7f-cc9e-4111-b29f-e59e3e64a33c.jpg)

**Comment by simonpoole** [comment]
Support for per value deprecation is relatively new, feel free to create a pull request with appropriate changes.

**Comment by simonpoole** [comment]
Still waiting for a pull request.
