### ISSUE TITLE
josm_preset.xml and new_josm_preset.xml are v2.1.0 (in the list of release assets)

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#386]
I believe since v5.0.2 the josm_preset.xml and new_josm_preset.xml files (in the list of release assets) are not the current version but v2.1.0. The current version of the JOSM preset is only available in the josm.zip file. Is there any reason, or is it wrong? (I also don't know what new_josm_preset.xml is - there's no explanation.)

**Comment by simonpoole** [comment]
The files where just left overs from previous versions in the directory used to collect that artifacts for publishing, the most recent release has them removed.
