### ISSUE TITLE
"Customers" value

### ISSUE THREAD

**Issue by Mannivu** [simonpoole/beautified-JOSM-preset#401]
## Vespucci Version
19.0.3.0

## Download source
Google Play Store 

## Device (Manufacturer and Model)
Xiaomi Redmi Note 11 Pro

## Android Version 
MIUI V14.0.1.0.TGDEUXM (Android 13)

## Behaviour/Symptoms
When selecting the "Customers" value from the "Access" presets the app incorrectly insert the "`customer`" (without the "s" at the end) value, wich is incorrect 

## Expected Behaviour
The app should insert "`customers`"

## How to recreate
On a random POI or highway try to insert "Customers" from the "Access" presets

## Crash dump submitted (no or yes + date)
No

## Any other potentially relevant information
none

**Comment by simonpoole** [comment]
This value was added long before there was agreement on even having the value, unluckily the people promoting it in the end didn't stick to normal OSM conventions and use the singular.
