### ISSUE TITLE
en-au translations

### ISSUE THREAD

**Issue by andrewharvey** [simonpoole/beautified-JOSM-preset#430]
I've requested the en-au language on the Presets project on OpenStreetMap on Transifex.

This would allow us to localise Vespucci presets to locally known terms to make them easier to find and understand for new users.

**Comment by simonpoole** [comment]
Hi Andrew

Just FYI just so that you know how lucky you are: transifexs language variant support sucks. It will work for variants of English as that is the original language of the project, but for any other language it requires a complete independent translation which is a massive PITA. :-)
