### ISSUE TITLE
Type of item "Public Market" (amenity=marketplace)

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#437]
According to the [Wiki](https://wiki.openstreetmap.org/wiki/DE:Tag:amenity%3Dmarketplace), type should be `type="node,closedway,multipolygon"` (now it's `type="node,way,closedway"`).

**Comment by simonpoole** [comment]
You can argue about the multipolygon, but excluding linear features is clearly wrong and can be traced back to a well known wikifiddler.

**Comment by jajajaneeneenee** [comment]
Hmmm ... OK ... then openway should be possible for `amenity=marketplace`? Really "clearly wrong" to exclude that? What makes it so clear to you? I'm thinking about what that might look like. A line parallel to a street (as is possible, for example, with `public_transport=platform`)? Or as an additional tag ON a highway (openway) line? I never saw something like this, but perhaps it exists. Hard to query for something like that with OverpassTurbo. I first tried with the [Wizard query](http://overpass-turbo.eu/s/1HCU) `amenity=marketplace AND highway=* AND highway!=pedestrian AND type:way global` and I found very very few examples of openways.

- Query result was 59 ways of 82.832x amenity=marketplace in all types, but most of them closedways, too – OverpassTurbo says: 23 ways and 36 polygons – and I didn't check all 59 results ...), 
- Without excluding `highway!=pedestrian` (mostly areas) the result is 32 ways and 392 polygons
- A [query](http://overpass-turbo.eu/s/1HCZ) without highway=* (`amenity=marketplace AND type:way global)` results in **56** ways (I think this means openways) and 47.789 polygons (40 MB query result).
- If it is really used only 56x worldwide on openways, this corresponds to a percentage of approx. 0.07% (56 of 82.832x amenity=marketplace). Not what I expected for a "clear" include of openways ... But not 100% sure, if my query or the interpretation of the query is correct ...

But here are 2 examples for openways:

- [https://www.openstreetmap.org/way/364701658](https://www.openstreetmap.org/way/364701658)
- [https://www.openstreetmap.org/way/1085958231](https://www.openstreetmap.org/way/1085958231) (maybe a mistake, because there is a node for the marketplace a bit apart – [https://www.openstreetmap.org/node/6083420708](https://www.openstreetmap.org/node/6083420708))

Here is a multipolygon by the way (a somehow strange one):
- https://www.openstreetmap.org/relation/6728193

And I saw in the [version history](https://wiki.openstreetmap.org/w/index.php?title=Tag%3Aamenity%3Dmarketplace&type=revision&diff=1515998&oldid=1470629) of the Wiki that it was "onWay = yes" until 2017-10-18 (then changed by user Geozeisig) ... There are often corrections to the type in the wiki – and usually justified (I therefore rely quite a bit on what is stated in the wiki, although of course that doesn't always have to be correct).

And the description in the Wiki also says: "Set a node or draw as an area along the outline of the marketplace and add amenity=marketplace". (But also added by user Geozeisig in 2017-10).

I would think, that somebody else would have changed this again since 2017 if it is really wrong (or a good practise to use it on openways, too) ... but who knows ... It looks for me like some kind of an agreement, that the best practice is to use it on a node or on a closedway (or multipolygon) and that it should be avoided to use it on a closedway. (Seems to have a logic to me when I think about rendering, where in a marketplace it might often make sense to display an icon. Difficult on an openway.)

However, the proposal from 2009 says nothing about the type ...
