### ISSUE TITLE
departures_board:speech_output

### ISSUE THREAD

**Issue by SomeoneElseOSM** [simonpoole/beautified-JOSM-preset#442]
Currently, `departures_board` is part of `public_transport=platform` and can be added via a button in the "properties" list to e.g. `highway=bus_stop`.  It'd be great if when adding `departures_board` you were also prompted for a value for `departures_board:speech_output` with the options `yes` ans `no` (but by default unset.  [Taginfo](https://taginfo.openstreetmap.org/keys/departures_board:speech_output#values), [wiki page](https://wiki.openstreetmap.org/wiki/Key%3Adepartures_board%3Aspeech_output).

I'm not sure what this means for implementation (in [master_preset.xml](https://github.com/simonpoole/beautified-JOSM-preset/blob/master/master_preset.xml) I can see `<chunk id="departures_board">`, hence adding it as an issue rather than a pull request.

**Comment by simonpoole** [comment]
chunks are simply reusable bits of config, in this case it used both in the item "Departure board" and in the platform chunk:  https://github.com/simonpoole/beautified-JOSM-preset/blob/master/master_preset.xml#L6322 and https://github.com/simonpoole/beautified-JOSM-preset/blob/master/master_preset.xml#L2387 The platform chunk is reused in lots of the public transport items.
