### ISSUE TITLE
Needs a bicycle parking present

### ISSUE THREAD

**Issue by vespucci-reporter** [simonpoole/beautified-JOSM-preset#443]
Description:
---

Maybe there is a preset already but I created a node and tried searching for "bike" and "bicycle" and nothing showed up. I couldn't remember how to tag it manually at the time. 

Device info:
---
<table>
<tr><td>App version</td><td>20.0.0.0</td></tr>
<tr><td>App version code</td><td>2801</td></tr>
<tr><td>Android build version</td><td>R.171e77d-c19c-4fe22</td></tr>
<tr><td>Android release version</td><td>14</td></tr>
<tr><td>Android SDK version</td><td>34</td></tr>
<tr><td>Android build ID</td><td>KB2003_14.0.0.501(EX01)</td></tr>
<tr><td>Device brand</td><td>OnePlus</td></tr>
<tr><td>Device manufacturer</td><td>OnePlus</td></tr>
<tr><td>Device name</td><td>OnePlus8T</td></tr>
<tr><td>Device model</td><td>KB2003</td></tr>
<tr><td>Device product name</td><td>OnePlus8T_EEA</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Aerond"/>Aerond</A></td></tr>
</table>

**Comment by simonpoole** [comment]
There is both the standard preset for bicycle parking in the default configuration in transport/bicycle that can be found by searching for "bicycle parking" (there are a lot of items that match "bicycle" and it is simply coincidence that bicycle parking doesn't get in the top 10), and there is a special demo version of the same with large images available as a custom preset https://vespucci.io/help/en/Presets/#useful-presets-for-download (that page is available via the on device help aswell).
