### ISSUE TITLE
Incorrect change at item "Set to disused"?

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#450]
In this [commit](https://github.com/simonpoole/beautified-JOSM-preset/commit/679e3b9f9a4094d478a80c0efb740054a4057f53) you changed` if (objects[i].equals(key)) {` to `if (objects[i].equalckey)) {`. 

Was this perhaps an unintentional change?

**Comment by simonpoole** [comment]
Unluckily it is not really practical to check the JS in CI so any such brokeness really can only be detected in actual use.
