### ISSUE TITLE
update `street_lamp` preset with more fields per osm doc

### ISSUE THREAD

**Issue by gena01** [simonpoole/beautified-JOSM-preset#451]
please update `street_lamp` preset:
https://github.com/simonpoole/beautified-JOSM-preset/blob/1a49e74a519d5f251532fd29f55fb01bd10dc3a1/master_preset.xml#L11054

to have more fields to make mapping easier, per: https://wiki.openstreetmap.org/wiki/Tag:highway%3Dstreet_lamp

**Comment by simonpoole** [comment]
What do you believe is missing?

**Comment by gena01** [comment]
I would add `support` to make it easier for me to map these. Some of the current values for `lamp_mount` would also overlap with `support` tag. 

iD editor allows you to set: support, mount, direction, height and "reference code".
