### ISSUE TITLE
Wrong name of new group “Climbing“

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#454]
In the last [commit](https://github.com/simonpoole/beautified-JOSM-preset/commit/faaef8ac476ee737f669517954a98bfc4b101e19) of June, 2, `<group name="Climbing" icon="${sport_climbing_site}">` was added, but in the final JOSM/Vespucci XML files, it's `<group name="Climbing site" icon="sport_climbing_21005.png">` now.

**Comment by simonpoole** [comment]
Fixed latest in 5.55.0
