### ISSUE TITLE
Issues with the new item “Pump track”

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#464]
There are 2 issues:

1. In the new item “Pump track” a text attribute is missing in the multiselect for key “sport”:

`<multiselect key="sport" values="bmx;skateboard" display_values="BMX;Skateboard" values_context="sport"/>`

2. The item does not match in Vespucci (`cycling=pump_track`, `cycling` is not an object key) – or should it only be used with `leisure=track` or `leisure=pitch`?

**Comment by simonpoole** [comment]
Fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/18c99ae50d75bfe9859ffec22c9fe41d1470ee36
