### ISSUE TITLE
The text “For traffic direction“ in chunk “traffic_signals_direction“ should be changed

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#467]
The key `direction` i the in chunk `"traffic_signals_direction"` has this text attribute: `text="For traffic direction"` and the values `"forward,backward,N,E,S,W,0,90,180,270"`. It is used for example for items like "Traffic sign".

```
    <chunk id="traffic_signals_direction">
        <combo key="direction" text="For traffic direction" values="forward,backward,N,E,S,W,0,90,180,270"
               display_values="Forward,Backward,North,East,South,West,0°,90°,180°,270°" values_sort="false" />
    </chunk>
```

But this text is not correct, if a traffic_sign node is mapped as a SEPARATE node (not on a way). Then the direction key should be a cardinal or angle value for the FACING orientation of the sign (= the direction the front of a sign faces). So in this case it is not the direction of traffic (forward/backward).

traffic_sign nodes are really a special case, because `direction` can be `forward/backward` for nodes ON ways – probably the most common case! – OR a or a direction as a cardinal value or angle value for nodes BESIDE ways (and the combo is correctly defined for both cases).

The text should perhaps simply be `text="Direction"` or you could add an explanatory label text such as:

`<label text="For separate nodes (not on a way) use values in ° or a cardinal letter (like N/W/S/E) for the FACING orientation of the sign." />`

**Comment by simonpoole** [comment]
The preset format currently cannot distinguish between nodes that are mapped separately and way nodes, so there is no real alternative than to provide all values in the same item.

**Comment by jajajaneeneenee** [comment]
I know that (although it would be fine if it could be distinguished, of course) ... The values are not the problem, only the text (it only fits for ONE of the two cases).

**Comment by jajajaneeneenee** [comment]
You haven't changed it yet. Have I not explained what I mean well enough? Is something incomprehensible? You haven't given me any feedback yet as to whether you understand what I mean. 

To repeat: the text "For traffic direction" is simply not correct if it is a _separate_ traffic_sign node (not connected with a way). Then, the direction is the _facing direction_ of the traffic sign, not the _traffic direction_. This can, for example, lead to incorrect entries by mappers who may not be very familiar with traffic_sign nodes. And even for experienced users, it is an unnecessary text confusion when editing a separate node. It would irritate me at least (and of course I've already changed the text in my custom presets ...). I just want to share my experience.

You would have to change something with the wording of the text attribute there... There is no way around it.

I have already mentioned suggestions above. In such a somewhat difficult case, I think an explanatory label text above (or under) the key is not a bad idea (to help mappers and to avoid incorrect entries!), and a neutral text like `text="Direction"` for the key - as I have already written above.

I know it's not the smartest solution and I know that you can't distinguish between separately mapped nodes and way nodes on highway ways (at least for Vespucci I guess – for JOSM it's perhaps possible with its match_expression="search expression" for presets, because in JOSM's search expressions you can also use more complex MapCSS selectors – in expert mode – which could make the necessary distinction – but not sure if this also works in presets for JOSM, I never tried it out), so I guess the only (pragmatic) solution for both JOSM and Vespucci is a simple text/wording solution ... And hand over the responsibility for correct input to the user (who now has it too). At least better than leaving it as it is.

Or does it not make you happy?
