### ISSUE TITLE
drop payment:dogecoin

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#47]
Dogecoin has miniscule adoption beyond tipping on social media, payment:dogecoin tag is used 68 times worldwide.

I propose to remove it from preset to reduce clutter on adding payment:* tags.

**Comment by simonpoole** [comment]
Removed in https://github.com/simonpoole/beautified-JOSM-preset/commit/25ebbb5209bbbc4cac50abdc7d9f99f8e17d7d25
