### ISSUE TITLE
The 2 variants of the traffic_sign items do not seem to work properly in JOSM

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#477]
It's nice that match_expression is supported by Vespucci since v20.2.0, but the search expression used in the 2 variants of the traffic_sign items (for connected and separate nodes) do not seem to work properly in JOSM (in Vespucci they work – except that they don't seem to be evaluated for the Vespucci validator, e.g. for check keys that would only apply to ONE variant don't work properly).

The problem in JOSM with traffic_sign nodes: no matter if it is a separate node or a node connected to a highway, it always only matches the item "Traffic sign (separate)" with `match_expression="-child highway=*"`. The item "Traffic sign" with `match_expression="child highway=*"` (for connected nodes) never matches. With the effect that the wrong combo for the direction key is displayed for connected nodes.

[By the way, there are 2 spaces in the item name "Traffic sign (separate)".]

I don't understand why it doesn't work in JOSM – if the search expression is used directly in the JOSM search, it works perfectly. And the JOSM documentation is not very clear regarding the match_expressions (e.g. if all kinds of search expressions are supported or only some). See [https://josm.openstreetmap.de/wiki/TaggingPresets](https://josm.openstreetmap.de/wiki/TaggingPresets). To me it reads as if the complete JOSM search syntax should be supported (_“match_expression="search expression": additional criteria for matching primitives, specified in JOSM search syntax”_).

Could it be a JOSM bug? Or is `child` not supported in JOSM match_expressions for presets? I couldn't find it out. I only found out that the default JOSM presets unfortunately do not use match_expressions with `child`.

**Comment by simonpoole** [comment]
This is likely a JOSM "bug" as in it simply doesn't evaluate match_expression in all situations and when it doesn't it might be simply displaying the last item that matches from a object type point of view.

**Comment by jajajaneeneenee** [comment]
How bad ... will you report it to the JOSM ticket system?

I've played around with match_expressions for JOSM and found that it works reliably as long as it's about excluding or including individual (or multiple) keys/tags. Even when it's a very long expression, e.g. with lots of tags to exclude. An example is the item for “Power plant“ (without a known `plant:source` tag):

`match_expression="power=plant -(&quot;plant:source&quot;=biofuel|&quot;plant:source&quot;=biogas|&quot;plant:source&quot;=biomass|&quot;plant:source&quot;=coal|&quot;plant:source&quot;=diesel|&quot;plant:source&quot;=gas|&quot;plant:source&quot;=gasoline|&quot;plant:source&quot;=geothermal|&quot;plant:source&quot;=hydro|&quot;plant:source&quot;=nuclear|&quot;plant:source&quot;=oil|&quot;plant:source&quot;=osmotic|&quot;plant:source&quot;=solar|&quot;plant:source&quot;=tidal|&quot;plant:source&quot;=waste|&quot;plant:source&quot;=wave|&quot;plant:source&quot;=wind)"`

Expressions like this work well in JOSM (I have not had a single situation where it was not evaluated; even with even longer expressions – and there are no time delays or the like).

Hence the suspicion that `child` might not be supported at all (or if only this is not evaluated correctly in all situations). You might, perhaps, be able to see this by looking at JOSM's Java code (I don't have enough Java knowledge for that). Here's a JOSM changeset when it was added: [https://josm.openstreetmap.de/changeset/17662/josm](https://josm.openstreetmap.de/changeset/17662/josm). Perhaps this helps ...

**Comment by jajajaneeneenee** [comment]
Any answer to the question regarding the JOSM ticket system? Or did you stop answering questions? Not even at Christmas time?

I made another test today in JOSM and found out:

- An expression like `match_expression="child highway=*"` **never** matches in JOSM (or has a false result). No matter if it is a connected node or not. And also not, if there is only one variant of a preset with this match_expression (and no variant with `-child`) and you test it with a connected node.
- The expression `match_expression="-child highway=*"` on the other hand **always** matches (or has a true result).

I also tried with some changes to the syntax like `match_expression="child (highway=*)"` or `match_expression="child (highway)"` and so on ... It makes no difference.

**Comment by simonpoole** [comment]
Please open an issue with JOSM, obviously they need to have a look at the problem.

**Comment by jajajaneeneenee** [comment]
I just opened a ticket for JOSM: [https://josm.openstreetmap.de/ticket/24096](https://josm.openstreetmap.de/ticket/24096). I hope it is correctly worded (I thought you as a JAVA developer could probably describe it more clearly for the developers of JOSM). I hope future JOSM versions will support this. We'll see...

At the moment it should be clear that the traffic_sign presets in JOSM do not work as intended (and a special solution without two separate presets for JOSM would actually be required) – but perhaps this will soon be resolved by a change in JOSM. And maybe it's not your main focus that there are problems in JOSM, I don't know... Because I wouldn't say that this issue is resolved and could already be closed. (I think that traffic sign nodes in JOSM are always shown with values ​​from the chunk "traffic_sign_direction_standalone" and never with `forward|backward` from the chunk "traffic_sign_direction" – just because `match_expression="-child highway=*"` will always match and `match_expression="child highway=*` will never match).

I have to admin that I don't fully understand the criteria for closing a problem (maybe that's your secret?) ... Especially because the presets are called “beautified-JOSM-preset”. That’s why I wanted to contribute and draw attention to this special problem (even though it's not my main focus, too ... I'm glad it works well in Vespucci, but I also use JOSM a lot).
