### ISSUE TITLE
The item “Seamark” doesn't match in JOSM

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#478]
The item “Seamark“ for `Key:seamark:type` has a variable key matching with `<combo key="seamark:type" text="Seamark type">`. It works fine in Vespucci, but it does not match in JOSM.

For JOSM, it seems to need a `match="key"` attribute, because the default for combos in JOSM is `match="none"` (and for Vespucci the default seems to be `match="key"`). See [JOSM documentation](https://josm.openstreetmap.de/wiki/TaggingPresets) (_“Default is "keyvalue!" for `<key>` and "none" for `<text />`, `<combo />`, `<multiselect />` and `<check />`.”_)

Or alternatively `match="keyvalue"`, if only the specified values of the combo should match (I think `match="key"` makes more sense if there are other/new/unknown values).

And it would be nice if you could answer a question regarding Vespucci (I know, it's a little off-topic and would better be in the Vespucci repository): What are the `match` defaults in Vespucci for `<text />`, `<combo />`, `<multiselect />` and `<check />`? Is it perhaps:
* `match=key` for `<combo />`, `<multiselect />` and `<check />`?
* `match=none` for `<text />`?

It has confused me several times (when creating custom presets) and it would be nice if this information was added to the Vespucci documentation ([http://vespucci.io/tutorials/presets/](http://vespucci.io/tutorials/presets/)).

**Comment by jajajaneeneenee** [comment]
@simonpoole: Could you please be so kind and answer the question with the matching standard for combo/multiselect/check/text in Vespucci? It always causes me problems when creating custom presets (I'm also currently having the problem that a match="none" doesn't work as expected with a multiselect – e.g. it still matches with an unknown value).

**Comment by simonpoole** [comment]
The Vespucci default is always keyvalue, see https://github.com/MarcusWolschon/osmeditor4android/blob/master/src/main/java/de/blau/android/presets/PresetItem.java#L1184 Note there is no guarantee that matching in Vespucci and JOSM returns the same results even if the same match values are used.
