### ISSUE TITLE
make opening hours tag optional for parking

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#48]
Parkings may have opening hours but typical one will be always open, do requiring it always seems to be a poor idea.

Moved from https://github.com/MarcusWolschon/osmeditor4android/issues/645

**Comment by simonpoole** [comment]
Fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/65fab547190ccedd6dd626e0fbaa61593cc6d760
