### ISSUE TITLE
Different meanings of "Island" need separate translation strings

### ISSUE THREAD

**Issue by kielein** [simonpoole/beautified-JOSM-preset#49]
The text "Island" is used in three places. The following two are together on transifex:
1. master_preset.xml:106(list_entry:short_description|value:island):
2. master_preset.xml:11659(item:name|group:Geography|preset:Island):

The third is alone in a separate text:
3. master_preset.xml:1941(item:name|group:Traffic_Calming|preset:Island):

In Finnish I would translate 1 and 3 with the same word ("saareke") and 2 with another ("saari").

Maybe it would be the best to split 1 and 2, i.e. have three individual translations strings.

**Comment by simonpoole** [comment]
Fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/ca8322ba2e3a711c7e01eeb574f049c407172335
