### ISSUE TITLE
optional names

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#51]
I think that for following names also should be optional:

natural=wetland

natural=mud

man_made=pier

leisure=slipway

aerialway=pylon

amenity=taxi

tourism=viewpoint

leisure=dog_park

tourism=picnic_site

**Comment by simonpoole** [comment]
Done in https://github.com/simonpoole/beautified-JOSM-preset/commit/9424cfa11d50170eff528c5ec69d976156a6c672

Note slipway and picnic_site the name field was already optional
