### ISSUE TITLE
mention ~/.transifexrc in README

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#54]
Initially gradle build was failing with because `tx` was missing, what I fixed by `sudo apt install transifex-client`

`17:37:14.203 [ERROR] [system.err] Exception: No user credentials found for host https://www.transifex.com. Edit ~/.transifexrc and add the appropriate info in there.`

It seems that file described in https://docs.transifex.com/client/client-configuration must be manually created.

**Comment by simonpoole** [comment]
Added in https://github.com/simonpoole/beautified-JOSM-preset/commit/306416328c30f5188939c49a9c9e95690d47a76c
