### ISSUE TITLE
Key:playground missing

### ISSUE THREAD

**Issue by AntonGut** [simonpoole/beautified-JOSM-preset#55]
Would it be possible to add Key:playground according to the following link?
https://wiki.openstreetmap.org/wiki/Key:playground

**Comment by HolgerJeromin** [comment]
There are [josm presets](https://josm.openstreetmap.de/wiki/Presets) available which i added to my vespucci.

**Comment by simonpoole** [comment]
@AntonGut the short term workaround would be to use the JOSM preset as suggested by @HolgerJeromin , I do however have to agree that they seem to not be particularly easy to use. Are you mainly looking at tagging individual equipment (the main issue is creating reasonable icons)?

**Comment by RedEye2063** [comment]
Is it possible to simply create a dropdown list for the key "playground" with all the values (sandpit, slide, swing etc.)? Or is a presset necessary for a dropdown?

**Comment by simonpoole** [comment]
Added in https://github.com/simonpoole/beautified-JOSM-preset/commit/6e39b1b039cabe05c6f60d7c86f0819300cfe290
