### ISSUE TITLE
Add religion=christian and outlet popular religions to amenity=place_of_worship

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#57]

**Comment by matkoniecz** [comment]
Outlet->other

**Comment by simonpoole** [comment]
You can actually edit the title of an issue :-)

**Comment by simonpoole** [comment]
In any case this would only be a useful change if you were changing a non-popular religion place of worship to a popular one, which is however already possible by using the fixed value presets http://simonpoole.github.io/beautified-JOSM-preset/#Place%20of%20Worship

The other way around will always require "manual" tag editing as fixed value presets will always match with higher precedence than variable value presets (and nothing else makes any sense), as was explained in the context of the recent building preset change.

**Comment by matkoniecz** [comment]
> if you were changing a non-popular religion place of worship to a popular one, 

I encountered it during creating a brand new one PoW. What about this usecase?

> You can actually edit the title of an issue :-)

I know, but I run into mobile browser/github bug :)

**Comment by simonpoole** [comment]
Brand new PoW: either select one of the 'popular' religion poW preset or the generic one. While you could argue that you should be able to add the popular ones via the generic, entry the specific ones have appropriate denomination values that should be set, so really make more sense to use. Yes, you could create an object via the generic preset, save and then re-edit (the specific preset would now match) but that would seem to be very convoluted compared to simply pressing the right button to start with.

Discussion of building preset: https://github.com/MarcusWolschon/osmeditor4android/issues/669

**Comment by matkoniecz** [comment]
So my method to manually enter amenity=place_of_worship and manually enter religion tag is not supposed to be used and I should search "Christian" worth pretty search...

**Comment by matkoniecz** [comment]
So my method to manually enter amenity=place_of_worship and manually enter religion tag is not supposed to be used and I should search "Christian" using preset search...

**Comment by simonpoole** [comment]
No, it is simply a different question (the religion values from the fixed presets should IMHO be added to the dropdown Vespucci if the main tag is the same), that I need to investigate.

**Comment by simonpoole** [comment]
After looking at it, this seems to be a bit of a goal conflict, as the code for the "Details" tab/form does actually use the limited range values from the preset once it is determined, instead of the complete list of values for the specific key (which exists as well). For now xing by using the full list in the "Other ... preset).

**Comment by simonpoole** [comment]
Addressed in https://github.com/simonpoole/beautified-JOSM-preset/commit/16ab113e346e0fa2476243c00c359167f8e18a81

**Comment by matkoniecz** [comment]
Thanks!
