### ISSUE TITLE
Support busway=* scheme

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#59]
See https://wiki.openstreetmap.org/wiki/Bus_lanes and https://wiki.openstreetmap.org/wiki/Key:busway

busway=lane/opposite_lane, busway:left=lane/opposite_lane, busway:right=lane/opposite_lane should be enough for start.

**Comment by simonpoole** [comment]
It is note quite clear to me why this should be anything else than deprecated, it conflicts with the lane tagging scheme (that has clearly "won" over other schemes for road tagging) in use all over the place and I can't quite see why it would be used for new tagging.

**Comment by matkoniecz** [comment]
> I can't quite see why it would be used for new tagging

In my case? Because I wanted to tag just busway without tagging all other lane properties. But maybe I should try again with lane tagging scheme.

**Comment by simonpoole** [comment]
I realize that this would be simpler than full lanes tagging, but, seriously, I don't think that it is realistic that it is going to go away :-)

**Comment by matkoniecz** [comment]
OK, next time I will try using https://wiki.openstreetmap.org/wiki/Key:lanes:psv
