### ISSUE TITLE
Support lanes:psv=* scheme

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#60]
As I understand #59 nowadays https://wiki.openstreetmap.org/wiki/Key:lanes:psv is used instead busway=*

I think that it would be a good idea to support this tagging scheme. As start, adding lanes:psv key to autocomplete and making it findable in "busway" search would be great, even without any support for any values.

**Comment by simonpoole** [comment]
Added in https://github.com/simonpoole/beautified-JOSM-preset/commit/51538ff8489214e7a913bda8d725abd330606c69

**Comment by matkoniecz** [comment]
Thanks!
