### ISSUE TITLE
Stop demanding name for shelters and shrines

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#63]
https://www.openstreetmap.org/way/255970982/history#map=17/49.29941/19.96170 - I am not sure why name is demanded here.

I would also expect most of historic=wayside_shrine to be unnamed - why name is required for this objects?

**Comment by simonpoole** [comment]
>why name is required for this objects? 
Because JOSM?

**Comment by simonpoole** [comment]
Fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/58db938917ce05cb48f63e96127a56d438e73759
