### ISSUE TITLE
make name optional for historic=building

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#65]
Old towns are typically filled with historic houses and only some are named - see http://overpass-turbo.eu/s/xdr (370 buildings without names).

**Comment by simonpoole** [comment]
Note on this (I'll make name optional in any case): I suspect marking these buildings as historic=building (which doesn't even have a wiki page) is a bit of a misuse. We have lots of medieval towns here where you could tag essentially every building as "historic" but they are in general not of special interest outside of being a couple of 100 years old and looking nice.

**Comment by simonpoole** [comment]
Done in https://github.com/simonpoole/beautified-JOSM-preset/commit/fe4b76c69eab888325b1b0d939eeb5a2127f7cfc

**Comment by matkoniecz** [comment]
> but they are in general not of special interest

I would expect ones of special interest to be tagged with tourism=attraction (like there are thousands of historic=wayside_cross while only some are of a special interest)
