### ISSUE TITLE
Add more tower:type

### ISSUE THREAD

**Issue by HolgerJeromin** [simonpoole/beautified-JOSM-preset#66]
https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dtower
https://wiki.openstreetmap.org/wiki/Key:tower:type
I miss Bell towers and lighting the most.
Thanks a lot

**Comment by simonpoole** [comment]
Added in https://github.com/simonpoole/beautified-JOSM-preset/commit/3f3288cb991e0ffcc52cc65fef4fb8eef98f3be7
