### ISSUE TITLE
 provide synonyms

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#69]
In Polish "budowa" means construction, so somebody who wants to use landuse=construction may search using this word

Unfortunately, Vespucci is unable to guess that it refers to this form as to make meaning clear it is named "teren budowy".

It would be desirable to allow adding synonyms for use by search.

I added "budowa" synonym in  presets.presets.landuse/construction.terms  iD translation entry in https://www.transifex.com/openstreetmap/id-editor/translate/#pl/presets/14390184?q=text%3Aconstruction but it is still not found in Vespucci.

It is related to #30, repeat of #4 that for some reason failed to fix this issue.

**Comment by matkoniecz** [comment]
From what I see in https://github.com/simonpoole/beautified-JOSM-preset/blob/master/i18n/preset_pl.po landuse=construction is not described as "budowa" in provided preset.

After switching to pl language building=construction is found (with poor description - "Budynek" means building, not "Building during construction", I wonder where I should fix/report it) and highway=construction is not found at all (what may be a Vespucci bug, I will for update to be sure before reporting).

**Comment by simonpoole** [comment]
I suspect this is simply because I haven't updated the synonyms from the iD repo for the last two public builds.

**Comment by simonpoole** [comment]
This seems to be found now.

**Comment by matkoniecz** [comment]
"budowa" and "budowa drogi" still finds nothing after changing language to Polish.

Vespucci 11.0.1
