### ISSUE TITLE
Strange grouping and sub-grouping in JOSM

### ISSUE THREAD

**Issue by Skippern** [simonpoole/beautified-JOSM-preset#7]
I discovered that JOSM is grouping the tags very strangely. Some groups that should be sub-groups end up as main groups (way, waypoint, access restrictions), and some groups and subgroups end up in groups where they do not belong (geography under highway, etc) Don't know exactly what makes this.

**Comment by simonpoole** [comment]
Is the grouping different than here: http://simonpoole.github.io/beautified-JOSM-preset/ ?

And with which JOSM version are you seeing the issues?

**Comment by Skippern** [comment]
JOSM 9060 (stable)

Yes, the grouping is different from  http://simonpoole.github.io/beautified-JOSM-preset/ 

In Highway "Streets" seems to be in the right place, but the other groups belonging there have been moved out to be main groups, all other groups seems to be in Highway, so that I have Highway/Geography, Highway/Man-made, Highway/Water, Highway/Transport, Highway/Sports, Highway/Office, etc

Highway/Streets is correct

Way, Waypoint, Access Restriction, etc. should have been in Highway but stands as Main Groups.

![untitled](https://cloud.githubusercontent.com/assets/802652/11701128/dff3b5aa-9eb4-11e5-9fb3-6fe2094fef20.png)

**Comment by simonpoole** [comment]
Fairly sure you still have the default JOSM preset enabled.

**Comment by Skippern** [comment]
Thats right, thats why they are all duplicated

**Comment by Skippern** [comment]
Removing the default style and the grouping seems correct, there must be some incompatibility between the two styles since it clashes like that. I knew that adding your style without removing the default would duplicate stuff, but didn't expect the re-grouping

**Comment by simonpoole** [comment]
Hmm likely a JOSm bug the groups are named the same, but that IMHO shouldn0t cause any problems (given that you can't gurantee that presets don't have colinding names in general).

**Comment by Skippern** [comment]
Maybe report it to JOSM?
