### ISSUE TITLE
Artifacts in SVG files

### ISSUE THREAD

**Issue by PanderMusubi** [simonpoole/beautified-JOSM-preset#70]
Files in `icons/svg-osm-icons` have some artifacts when viewed in Inkscape. See attached screenshots.

![2018-04-24-174513_1920x1080_scrot](https://user-images.githubusercontent.com/198964/39198673-eaea8f54-47e7-11e8-889f-fc841ab6768b.png)

![2018-04-24-174517_1920x1080_scrot](https://user-images.githubusercontent.com/198964/39198675-eb0d8108-47e7-11e8-9e62-116c1e166876.png)

![2018-04-24-174519_1920x1080_scrot](https://user-images.githubusercontent.com/198964/39198676-eb349ac2-47e7-11e8-9862-7af539656dcf.png)

**Comment by simonpoole** [comment]
I did a couple of sport checks however didn't see anything like that, which svg-file did you use as a template?

**Comment by PanderMusubi** [comment]
Unfortunately, the error is still there. The line that is the outline hasn't been closed.
