### ISSUE TITLE
For objects with mandatory names add noname=yes to presets

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#72]
For example with shop=convenience: noname=yes is not in the preset and name is demanded by validator in Vespucci.

**Comment by simonpoole** [comment]
https://github.com/simonpoole/beautified-JOSM-preset/commit/9209fd86056237ec1fd3223c83754626eed626d4 adds a "No name" utility preset item, and adds links to it for lots of objects.
