### ISSUE TITLE
allow no value for service:bicycle:repair

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#76]
very similar to #40 

service:bicycle:repair = no is useful to note that no repairs are offered

also other values from this family are likely to be useful with no value - https://wiki.openstreetmap.org/wiki/Tag:shop%3Dbicycle#Additional_keys

**Comment by simonpoole** [comment]
Addressed in https://github.com/simonpoole/beautified-JOSM-preset/commit/8bf6085de70c5bb5dbd0d7ac39c8311df3f3b294
