### ISSUE TITLE
shop=pastry icon may use icon for shop=confectionery from openstreetmap-carto

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#80]
In this map style patry and confectionery share icon that fits pastry well.

https://wiki.openstreetmap.org/wiki/Tag:shop%3Dpastry#/media/File%3AConfectionery-14.svg

https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/confectionery.svg

CC0 licence

**Comment by simonpoole** [comment]
Added in https://github.com/simonpoole/beautified-JOSM-preset/commit/389ec2af26d321850aaa85a21cc46880c9c04680 thanks for the pointer.
