### ISSUE TITLE
add shop=pottery and shop=spices

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#83]
From what I see https://wiki.openstreetmap.org/wiki/Tag:shop%3Dspices and https://wiki.openstreetmap.org/wiki/Tag:shop%3Dpottery and are accepted, documented values not converted by other shop values already present in Vespucci.

I can confirm that many unmapped shops of this type exists.

Iconless entry would be great to add.

**Comment by simonpoole** [comment]
Added to https://github.com/simonpoole/beautified-JOSM-preset/issues/35

**Comment by matkoniecz** [comment]
Would you accept PR adding this two shops without icon (so it would be like shop=pastry before #80)?

**Comment by simonpoole** [comment]
Sure (pottery could likely use a version of the craft=pottery icon)
