### ISSUE TITLE
make names optional for highway=footway

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#84]
I reinstalled & updated Vespucci (to reset settings) and it started to demand name for highway=footway

**Comment by simonpoole** [comment]
The names are optional for all minor stuff .... this looks like a bug in the vespucci beta (assuming that was what you are using), that's what betas are for.

**Comment by matkoniecz** [comment]
> that's what betas are for

I know, I enabled beta because I have no trouble with reporting bugs. I just thought that bug is in presets and that beta pulled in new buggy presets.
