### ISSUE TITLE
make name optional for natural=water, water=reservoir

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#85]
Reported after encountering https://www.openstreetmap.org/way/247953948/history#map=15/50.2196/19.1112 - this type of object generally has no names

Not sure is it feasible to do but maybe expect names only for big reservoirs?

**Comment by simonpoole** [comment]
Indirectly fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/9570738a8480962ac331c6c3b5c352f4a78c7326
