### ISSUE TITLE
better quarry colouring

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#87]
Change green landuses=quarry to gray or brown or purple or anything not green
Maybe change green landuse=quarry to gray or brown? Or dark purple?

Grey may be easy to confuse with residential, but it is better than looking like a forest.

**Comment by simonpoole** [comment]
Wrong repo :-)

You can simply make a copy of https://github.com/MarcusWolschon/osmeditor4android/blob/master/src/main/assets/Color-round-profile.xml , add an entry and copy it to your vespucci directory, using a different name. The format is completely undocumented, but it should be obvious :-). Once you are happy you can make PR (make the same change to Pen-round-profile.xml too).

**Comment by matkoniecz** [comment]
> the format is a hack, there is a very old issue to write a mapcss parser and add better object matching

I know, that is why I limited issue to changing colour (that should be useful also after adding mapcss parser).

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/981bfa1be657e0b1df5d34494ba42a69e8070470
