### ISSUE TITLE
change landuse names to "xyz area"

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#88]
Currently after searching "industrial" one gets "industrial" (for landuse) and "industrial" (for building).

They also have the same shape for an icon.

Icon colour is different but it is completely unclear for new users and unclear even for experienced.

I suggest changing names to "industrial area" and "industrial building".

**Comment by simonpoole** [comment]
Done in https://github.com/simonpoole/beautified-JOSM-preset/commit/16d0b3dd38b16ddc118f20fde0d63942740ce2c3
