### ISSUE TITLE
add material=wood to material preset

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#89]

**Comment by simonpoole** [comment]
Which preset do you mean exactly? There are lots of material tags with different lists of values, because it depends strongly on the subject matter.

**Comment by matkoniecz** [comment]
I was tagging a church made of wood. Now I see that current preset has building:material tag.

https://taginfo.openstreetmap.org/tags/material=wood#combinations indicates that material=wood is not popular for buildings.

I think that it can be closed, I was editing in raw tag editor so clever hints from beautified editor would not help anyway...
