### ISSUE TITLE
Government offices tagging scheme approved

### ISSUE THREAD

**Issue by Teiron** [simonpoole/beautified-JOSM-preset#9]
With the new tagging scheme described here [link](http://wiki.openstreetmap.org/wiki/Proposed_features/Government_offices) number of presets are now outdated and should be changed. This include:

```
preset name; old tagging; new tagging
Register; office=register; office=government + government=register_office
Administrative; office=administrative; office=government
Public buildng; amenity=public_building; discouraged
```

From what I seen that should be it, but if someone could double check it I would be grateful.

**Comment by simonpoole** [comment]
There's a general issue with such changes with the JOSM preset system that I need to address, on the one hand old tagging schemes need to stay around, particularly when they have been in real use (9500 uses of office=administrative for example), to support automatically matchinf and identifying such objects, on the other hand there is no way to programatically indicate preferred/new tagging. This will likely need some non-JOSM compatible extensions which will have to be stripped out for use with JOSM.

**Comment by Teiron** [comment]
> there is no way to programatically indicate preferred/new tagging,
I know that might be beyond scope of this repository, but I think iD editor marks it's obsolete presets with unsearchable tag so it's still in use on map and during edition of existing features, yet it can't be selected for new ones.

**Comment by simonpoole** [comment]
https://github.com/simonpoole/beautified-JOSM-preset/commit/1f0c5ea35ded227f72530dc5749d01ccd1ec3ba7 we've supported a deprecated flag gor quite a while now.
