### ISSUE TITLE
transifex configuration issues

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#93]
I attempted to build presets (as the first step toward making some PRs) but I run into issues with some utterly unclear ```tx ERROR: Not Found``` . There is also ```tx ERROR: Resource vespucci.preset-pot doesn't exist on the server.``` that sounds like something unfixable from my side.

Answers to configuration questions were in part guessed, so maybe I made some sort of a mistake.

I configured tx and pulled translation as logged in https://gist.github.com/matkoniecz/023027e991e9fc6fe0a2e7d34d466866

And maybe this errors should be ignored.

**Comment by simonpoole** [comment]
You should be using the project transifex config https://github.com/simonpoole/beautified-JOSM-preset/blob/master/.tx/config (that maps language codes to Android ones and doesn't retrieve the .pot file which you don't actually want in any case).

**Comment by matkoniecz** [comment]
Hmmm, so you don't need to configure mapping at all - just login data like an API key (I see no way to reset transifex settings and start to scratch to see what exactly one should answer - and I wanted to update README).

From my log I see that `Enter the path to your local source file:`, `Enter a path expression:`, `Select the file format type`, `Select the organization to use`, `Select the project to use` seem to be ones that should be skipped.

**Comment by simonpoole** [comment]
https://github.com/simonpoole/beautified-JOSM-preset/commit/3172987746bdb2e9544b54d0bc96929a6d06d7ac
