### ISSUE TITLE
access field should be on top of list of fields in amenity=parking preset

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#95]
"Park and Ride" field is far less important, max height is relevant very rarely. Both are listed before very important access field that always should be filled.

**Comment by simonpoole** [comment]
I've moved the max height down, but would note that its importance depends very much n what kind of vehicle you are driving. Changed in https://github.com/simonpoole/beautified-JOSM-preset/commit/3d5f6287b49f4703f2dff506f4e36f242f3932be

**Comment by matkoniecz** [comment]
I would suggest moving down also park_ride field
