### ISSUE TITLE
inconsistent newlines

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#97]
From what I see some lines have LF, some CRLF in master_preset.xml - and it is not clear whatever I should ignore it or to keep care to not change existing newlines in PRs.

**Comment by simonpoole** [comment]
xml doesn't care really, and I haven't bothered to check if all editors doing the same up to now. IMHO it would be best to change to LF only, I can bulk reformat that which makes more sense that PRing changes.

**Comment by matkoniecz** [comment]
Are you still preferring to reformat on your own? Making PR for this one would be trivial and I can do it.

**Comment by simonpoole** [comment]
As the complete master source file has been run through a xsl transformation now, I assume that this is now moot.
